// Introspects the Neon Postgres database and writes a readable snapshot to
// backend/db/SCHEMA.md — tables, columns, keys, and live row counts.
//
//   dart run backend/db/introspect.dart
//
// Reads DATABASE_URL from the environment or from `.env` at the repo root.
// Read-only: it runs SELECTs against the catalog only, nothing is changed.

import 'dart:io';

import 'package:postgres/postgres.dart';

Future<void> main() async {
  final url = _databaseUrl();
  if (url == null || url.isEmpty) {
    stderr.writeln('DATABASE_URL not found (env or .env at repo root).');
    exit(1);
  }

  final uri = Uri.parse(url);
  final userInfo = uri.userInfo.split(':');
  final conn = await Connection.open(
    Endpoint(
      host: uri.host,
      port: uri.hasPort ? uri.port : 5432,
      database: uri.pathSegments.isNotEmpty ? uri.pathSegments.first : 'neondb',
      username: Uri.decodeComponent(userInfo.first),
      password: userInfo.length > 1 ? Uri.decodeComponent(userInfo[1]) : null,
    ),
    settings: const ConnectionSettings(
      sslMode: SslMode.require,
      applicationName: 'shield-introspect',
    ),
  );

  final buf = StringBuffer();

  final meta = (await conn.execute(
    'select version(), current_database(), current_user, now()',
  )).first;
  buf.writeln('# Neon database — schema snapshot');
  buf.writeln();
  buf.writeln('- **Server:** ${meta[0]}');
  buf.writeln('- **Database:** `${meta[1]}`  ·  **Role:** `${meta[2]}`');
  buf.writeln('- **Host:** `${uri.host}`');
  buf.writeln('- **Captured:** ${meta[3]}');
  buf.writeln();
  buf.writeln('> Generated by `dart run backend/db/introspect.dart`. '
      'Read-only snapshot; do not edit by hand.');
  buf.writeln();

  final tables = (await conn.execute(
    "select table_name from information_schema.tables "
    "where table_schema = 'public' and table_type = 'BASE TABLE' "
    "order by table_name",
  )).map((r) => r[0] as String).toList();

  // Row counts.
  final counts = <String, int>{};
  for (final t in tables) {
    final c = await conn.execute('select count(*) from "$t"');
    counts[t] = (c.first.first as int);
  }

  final withData = tables.where((t) => counts[t]! > 0).toList();
  final empty = tables.where((t) => counts[t]! == 0).toList();

  buf.writeln('## Overview');
  buf.writeln();
  buf.writeln('- **${tables.length}** tables in `public`');
  buf.writeln('- **${withData.length}** hold rows, **${empty.length}** are empty');
  buf.writeln();
  buf.writeln('| Table | Rows |');
  buf.writeln('| --- | ---: |');
  for (final t in tables) {
    buf.writeln('| `$t` | ${counts[t]} |');
  }
  buf.writeln();

  // Columns.
  final cols = await conn.execute(
    "select table_name, column_name, data_type, is_nullable, column_default "
    "from information_schema.columns where table_schema = 'public' "
    "order by table_name, ordinal_position",
  );
  final byTable = <String, List<List<Object?>>>{};
  for (final r in cols) {
    (byTable[r[0] as String] ??= []).add(r.toList());
  }

  // Primary keys.
  final pkRows = await conn.execute(
    "select tc.table_name, kcu.column_name "
    "from information_schema.table_constraints tc "
    "join information_schema.key_column_usage kcu "
    "  on kcu.constraint_name = tc.constraint_name "
    " and kcu.table_schema = tc.table_schema "
    "where tc.table_schema = 'public' and tc.constraint_type = 'PRIMARY KEY' "
    "order by tc.table_name, kcu.ordinal_position",
  );
  final pk = <String, List<String>>{};
  for (final r in pkRows) {
    (pk[r[0] as String] ??= []).add(r[1] as String);
  }

  // Foreign keys.
  final fkRows = await conn.execute(
    "select tc.table_name, kcu.column_name, "
    "       ccu.table_name as ref_table, ccu.column_name as ref_column "
    "from information_schema.table_constraints tc "
    "join information_schema.key_column_usage kcu "
    "  on kcu.constraint_name = tc.constraint_name "
    " and kcu.table_schema = tc.table_schema "
    "join information_schema.constraint_column_usage ccu "
    "  on ccu.constraint_name = tc.constraint_name "
    " and ccu.table_schema = tc.table_schema "
    "where tc.table_schema = 'public' and tc.constraint_type = 'FOREIGN KEY' "
    "order by tc.table_name, kcu.column_name",
  );
  final fk = <String, List<List<String>>>{};
  for (final r in fkRows) {
    (fk[r[0] as String] ??= []).add(
      [r[1] as String, r[2] as String, r[3] as String],
    );
  }

  buf.writeln('## Tables');
  buf.writeln();
  for (final t in tables) {
    buf.writeln('### `$t`  ·  ${counts[t]} rows');
    buf.writeln();
    final keys = pk[t];
    if (keys != null) buf.writeln('- Primary key: ${keys.map((k) => '`$k`').join(', ')}');
    for (final f in fk[t] ?? const <List<String>>[]) {
      buf.writeln('- FK `${f[0]}` → `${f[1]}.${f[2]}`');
    }
    buf.writeln();
    buf.writeln('| Column | Type | Null | Default |');
    buf.writeln('| --- | --- | --- | --- |');
    for (final c in byTable[t] ?? const <List<Object?>>[]) {
      final def = (c[4]?.toString() ?? '').replaceAll('|', r'\|');
      buf.writeln('| `${c[1]}` | ${c[2]} | ${c[3]} | ${def.isEmpty ? '' : '`$def`'} |');
    }
    buf.writeln();
  }

  await conn.close();

  final out = File('backend/db/SCHEMA.md');
  out.writeAsStringSync(buf.toString());
  stdout.writeln('Wrote ${out.path}  '
      '(${tables.length} tables, ${withData.length} with data)');
  stdout.writeln();
  stdout.writeln('Tables holding rows:');
  for (final t in withData) {
    stdout.writeln('  ${t.padRight(38)} ${counts[t]}');
  }
}

String? _databaseUrl() {
  final env = Platform.environment['DATABASE_URL'];
  if (env != null && env.isNotEmpty) return env;
  final file = File('.env');
  if (!file.existsSync()) return null;
  for (final raw in file.readAsLinesSync()) {
    final line = raw.trim();
    if (line.isEmpty || line.startsWith('#')) continue;
    final eq = line.indexOf('=');
    if (eq <= 0 || line.substring(0, eq).trim() != 'DATABASE_URL') continue;
    var v = line.substring(eq + 1).trim();
    if (v.length >= 2 &&
        ((v.startsWith('"') && v.endsWith('"')) ||
            (v.startsWith("'") && v.endsWith("'")))) {
      v = v.substring(1, v.length - 1);
    }
    return v;
  }
  return null;
}
