// Writes `lib/data/neon/neon_secret.dart` from `DATABASE_URL` in `.env`.
//
//   dart run tool/gen_neon_secret.dart
//
// The app reads the connection string from that generated const, NOT from
// `--dart-define`: the URL contains `&`, and on Windows `flutter.bat` runs under
// cmd.exe, which treats `&` on the command line as a statement separator, so the
// define silently arrived truncated (or empty). A plain source const sidesteps
// the shell entirely. The generated file is git-ignored — it holds the DB
// password. Re-run this whenever `.env` changes.

import 'dart:io';

void main() {
  final env = File('.env');
  if (!env.existsSync()) {
    stderr.writeln('.env not found at the repo root. Copy .env.example first.');
    exit(1);
  }

  String? url;
  for (final raw in env.readAsLinesSync()) {
    final line = raw.trim();
    if (line.startsWith('#') || !line.contains('=')) continue;
    final eq = line.indexOf('=');
    if (line.substring(0, eq).trim() == 'DATABASE_URL') {
      url = line.substring(eq + 1).trim();
      if (url.length >= 2 &&
          ((url.startsWith('"') && url.endsWith('"')) ||
              (url.startsWith("'") && url.endsWith("'")))) {
        url = url.substring(1, url.length - 1);
      }
      break;
    }
  }

  if (url == null || url.isEmpty) {
    stderr.writeln('.env has no DATABASE_URL= line.');
    exit(1);
  }

  final escaped = url.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
  final out = File('lib/data/neon/neon_secret.dart');
  out.writeAsStringSync('''
// GIT-IGNORED — generated by `dart run tool/gen_neon_secret.dart` from `.env`.
// Holds the Neon database password. Do not edit by hand, do not commit.
//
// A source const rather than `--dart-define`: the URL contains `&`, which
// `flutter.bat` (cmd.exe) treats as a command separator on Windows, truncating
// the define. A const has no such problem and is identical in debug and release.

const String kNeonDatabaseUrl =
    '$escaped';
''');

  stdout.writeln('Wrote ${out.path} (${url.length} chars).');
}
