-- ============================================================================
--  0049 · Seed the lab test master with the reference-lab rate list
-- ============================================================================
--  525 single tests from the lab's rate list -- name, method, sample,
--  volume, scheduled days, cut-off time, reporting time, the patient rate and
--  the lab rate -- so lab users can pick them when they build a Group Test or
--  Package on the console's Lab Tests > Test Master tab, and edit any of them.
--
--  * Patient rate goes to rate / amount (no discount); lab rate to lab_rate.
--    A dash or blank in the list is stored as empty text or 0 ("not quoted").
--  * Department is not in the list, so it is left blank for the lab to fill in.
--  * Typos in the reporting-time column were tidied ("3rdDay" -> "3rd Day",
--    "3thDay" -> "3rd Day", "3r Day" -> "3rd Day", "7rd Day" -> "7th Day",
--    "10 Days" -> "10th Day", "One week" -> "1 week"). Anything else, such as
--    Platelet Antibodies' "Wed", is kept as the list has it.
--  * Immunohistochemistry has no rate in the list ("Please contact for more
--    details"); that text is kept as its internal note. Adrenaline
--    (Epinephrine) has no details at all, so only its name is stored.
--
--  Every row is tagged source = 'RATE_LIST' (see 0050) so the console keeps them
--  out of its Saved tests list while still offering them when a Group Test or
--  Package is built. Needs 0046 (the lab_test tables) and 0048 (scheduled_days,
--  reporting_time, lab_rate) applied first. Idempotent and safe to re-run: a test whose name
--  already exists (ignoring case) is skipped, never overwritten, so edits made
--  in the console survive. Lis Codes are handed out by the database.
--    dart run backend/db/apply_migration.dart backend/db/migrations/0049_seed_lab_test_rate_list.sql --yes
-- ============================================================================

SET search_path TO app, public;

-- Same column 0050 adds, so this seed works whichever of the two is applied first.
ALTER TABLE app.lab_test
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'ADMIN'
  CHECK (source IN ('ADMIN', 'RATE_LIST'));

INSERT INTO app.lab_test
  (test_type, name, method, sample, volume, scheduled_days, cut_of_time,
   reporting_time, rate, discount_percent, amount, lab_rate, internal_note,
   source, created_by, updated_by)
SELECT v.*, 'Rate list import', 'Rate list import'
FROM (VALUES
  ('TEST', '17-OH Progesterone (17-OHP)', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 800, 0, 800, 550, '', 'RATE_LIST'),
  ('TEST', 'Absolute Basophil Count (ABC)', 'Automated', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 60, 0, 60, 40, '', 'RATE_LIST'),
  ('TEST', 'Absolute Eosinophil Count (AEC)', 'Automated', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 60, 0, 60, 40, '', 'RATE_LIST'),
  ('TEST', 'Absolute Lymphocyte Count (ALC)', 'Automated', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 60, 0, 60, 40, '', 'RATE_LIST'),
  ('TEST', 'Absolute Monocyte Count (AMC)', 'Automated', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 60, 0, 60, 40, '', 'RATE_LIST'),
  ('TEST', 'Absolute Neutrophil Count (ANC)', 'Automated', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 60, 0, 60, 40, '', 'RATE_LIST'),
  ('TEST', 'ACE (Angiotensin Converting Enzyme)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 900, 0, 900, 600, '', 'RATE_LIST'),
  ('TEST', 'Acetone-Serum (Ketone Body)', 'Biochemical', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 600, 0, 600, 480, '', 'RATE_LIST'),
  ('TEST', 'Acetone-Urine (Ketone Body)', 'Chemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 60, 0, 60, 45, '', 'RATE_LIST'),
  ('TEST', 'Acetylcholine Receptor Antibody (AChR)', 'EIA', 'Serum', '2 ml', 'Tue, Thu, Sat', '1 pm', '3rd Day', 2700, 0, 2700, 2300, '', 'RATE_LIST'),
  ('TEST', 'Acetylcholinesterase', 'Biochemical', 'EDTA Plasma', '3 ml', 'Tue, Sat', '1 pm', '3rd Day', 1100, 0, 1100, 900, '', 'RATE_LIST'),
  ('TEST', 'Acid Phosphatase', 'Biochemical', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 300, 0, 300, 200, '', 'RATE_LIST'),
  ('TEST', 'Acid Phosphatase - Prostatic', 'Biochemical', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 400, 0, 400, 320, '', 'RATE_LIST'),
  ('TEST', 'ACTH (Adrenocorticotropic Hormone)', 'CLIA', 'EDTA Plasma', '2 ml', 'Daily', '1 pm', '3rd Day', 1100, 0, 1100, 850, '', 'RATE_LIST'),
  ('TEST', 'ADA (Adenosine Deaminase)', 'Biochemical', 'Serum/Body Fluids', '2 ml', 'Daily', '', 'Same Day', 600, 0, 600, 480, '', 'RATE_LIST'),
  ('TEST', 'ADH (Antidiuretic Hormone/Vasopressin)', 'RIA', 'EDTA Plasma', '2 ml', 'Fri', '1 pm', '6th Day', 5500, 0, 5500, 4800, '', 'RATE_LIST'),
  ('TEST', 'Adrenaline (Epinephrine)', '', '', '', '', '', '', 0, 0, 0, 0, '', 'RATE_LIST'),
  ('TEST', 'AFB Stain', 'Staining', 'Sputum/Urine/Body Fluids', '', 'Daily', '', 'Same Day', 150, 0, 150, 80, '', 'RATE_LIST'),
  ('TEST', 'AFP (Alpha-fetoprotein)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 500, 0, 500, 300, '', 'RATE_LIST'),
  ('TEST', 'Albert Stain', 'Staining', 'Swab', '', 'Daily', '', 'Same Day', 300, 0, 300, 170, '', 'RATE_LIST'),
  ('TEST', 'Albumin/Creatinine Ratio (ACR)-Urine (24 hrs)', 'Biochemical', '24 hrs Urine', '10 ml', 'Daily', '', 'Same Day', 450, 0, 450, 300, '', 'RATE_LIST'),
  ('TEST', 'Albumin/Creatinine Ratio (ACR)-Urine (Spot)', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 350, 0, 350, 250, '', 'RATE_LIST'),
  ('TEST', 'Albumin-Serum', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 80, 0, 80, 60, '', 'RATE_LIST'),
  ('TEST', 'Albumin-Urine', 'Dipstick', 'Urine', '10 ml', 'Daily', '', 'Same Day', 20, 0, 20, 15, '', 'RATE_LIST'),
  ('TEST', 'Alcohol- Serum (Ethanol)', 'Biochemical', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1100, 0, 1100, 850, '', 'RATE_LIST'),
  ('TEST', 'Alcohol- Urine (Ethanol)', 'LCMS/MS', 'Urine', '10 ml', 'Wed', '1 pm', '4th Day', 1100, 0, 1100, 900, '', 'RATE_LIST'),
  ('TEST', 'Aldolase', 'Biochemical', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 800, 0, 800, 700, '', 'RATE_LIST'),
  ('TEST', 'Aldosterone', 'CLIA', 'EDTA Plasma', '3 ml', 'Daily', '1 pm', '5th Day', 1800, 0, 1800, 1450, '', 'RATE_LIST'),
  ('TEST', 'Alkaline Phosphatase (ALP)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 100, 0, 100, 80, '', 'RATE_LIST'),
  ('TEST', 'Allergy Panel-Food', 'Immunoblot', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 5000, 0, 5000, 4200, '', 'RATE_LIST'),
  ('TEST', 'Allergy Panel Comprehensive - 63 Allergens', 'Immunoblot', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 6000, 0, 6000, 5000, '', 'RATE_LIST'),
  ('TEST', 'Allergy Panel Comprehensive - 107 Allergens', 'Immunoblot', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 7000, 0, 7000, 6000, '', 'RATE_LIST'),
  ('TEST', 'Allergy Panel-Inhalation or Respiratory', 'Immunoblot', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 6000, 0, 6000, 5000, '', 'RATE_LIST'),
  ('TEST', 'AMH (Anti-Mullerian Hormone)', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1400, 0, 1400, 1150, '', 'RATE_LIST'),
  ('TEST', 'Amino acids Qualitative-Plasma / Urine', 'TLC', 'Serum/ Sod Hep Plasma', '2 ml', 'Mon, Wed, Sat', '1 pm', '4th Day', 1500, 0, 1500, 1200, '', 'RATE_LIST'),
  ('TEST', 'Amino acids Quantitative-Plasma', 'LC-MS/MS', 'Sod Heparin Plasma', '2 ml', 'Mon, Sat', '1 pm', '5th Day', 5000, 0, 5000, 4400, '', 'RATE_LIST'),
  ('TEST', 'Amino acids Quantitative-Urine', 'LC-MS/MS', 'Urine', '10 ml', 'Mon, Sat', '1 pm', '5th Day', 5000, 0, 5000, 4400, '', 'RATE_LIST'),
  ('TEST', 'Ammonia', 'Biochemical', 'EDTA Plasma', '2 ml', 'Daily', '', 'Same Day', 550, 0, 550, 400, '', 'RATE_LIST'),
  ('TEST', 'Amphetamine', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Amylase-Serum', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 300, 0, 300, 150, '', 'RATE_LIST'),
  ('TEST', 'Amylase-Urine', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 300, 0, 300, 100, '', 'RATE_LIST'),
  ('TEST', 'ANA Profile', 'Immunoblot (LIA)', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 2500, 0, 2500, 1950, '', 'RATE_LIST'),
  ('TEST', 'ANA-ELISA', 'ELISA', 'Serum', '2 ml', 'Daily', '2 pm', 'Same Day', 500, 0, 500, 300, '', 'RATE_LIST'),
  ('TEST', 'ANA-IFA', 'IFA', 'Serum', '3 ml', 'Daily', '1 pm', 'Same Day', 900, 0, 900, 600, '', 'RATE_LIST'),
  ('TEST', 'ANCA(ANCA-P &ANCA-C Antibodies)', 'ELISA', 'Serum', '3 ml', 'Daily', '1 pm', 'Same Day', 1400, 0, 1400, 1100, '', 'RATE_LIST'),
  ('TEST', 'ANCA-C (PR3-ANCA)', 'ELISA', 'Serum', '3 ml', 'Daily', '1 pm', 'Same Day', 800, 0, 800, 650, '', 'RATE_LIST'),
  ('TEST', 'ANCA-P (MPO-ANCA)', 'ELISA', 'Serum', '3 ml', 'Daily', '1 pm', 'Same Day', 800, 0, 800, 650, '', 'RATE_LIST'),
  ('TEST', 'Androstenedione', 'RIA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 1500, 0, 1500, 1100, '', 'RATE_LIST'),
  ('TEST', 'Anemia Profile (CBC, TIBC, Iron, Ferritin, PBF)', 'Multiple Methods', 'EDTA Blood+Serum+Spot Smear', '3 ml', 'Daily', '', 'Next Day', 1500, 0, 1500, 1000, '', 'RATE_LIST'),
  ('TEST', 'Anti-Cardiolipin Antibodies (ACLA)-IgG & IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1200, 0, 1200, 800, '', 'RATE_LIST'),
  ('TEST', 'Anti-Cardiolipin Antibody (ACLA)-IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 650, 0, 650, 450, '', 'RATE_LIST'),
  ('TEST', 'Anti-Cardiolipin Antibody (ACLA)-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 650, 0, 650, 450, '', 'RATE_LIST'),
  ('TEST', 'Anti-CCP (ACCP)', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 900, 0, 900, 650, '', 'RATE_LIST'),
  ('TEST', 'Anti-dsDNA Antibody', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 650, 0, 650, 400, '', 'RATE_LIST'),
  ('TEST', 'Anti-Microsomal antibody (AMA/ATPO)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 500, 0, 500, 300, '', 'RATE_LIST'),
  ('TEST', 'Anti-MOG (Myelin Oligodendrocyte Glycoprotein) Antibody', 'IFA', 'Serum', '2 ml', 'Sat', '1 pm', '4th Day', 6500, 0, 6500, 5700, '', 'RATE_LIST'),
  ('TEST', 'Anti-MuSK (Muscle Specific Kinase) Antibody', 'EIA', 'Serum', '2 ml', 'Sat', '1 pm', '4th Day', 5500, 0, 5500, 4950, '', 'RATE_LIST'),
  ('TEST', 'Anti- NMO (Neuromyelitis Optica) Panel (Anti Aquaporin 4 Anti MOG)', 'Cell based assay, IFA', 'Serum', '2 ml', 'Sat', '1 pm', '4th Day', 6500, 0, 6500, 5700, '', 'RATE_LIST'),
  ('TEST', 'Anti-Phospholipid Antibodies (APLA)-IgG & IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1200, 0, 1200, 800, '', 'RATE_LIST'),
  ('TEST', 'Anti-Phospholipid Antibody (APLA)-IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 650, 0, 650, 450, '', 'RATE_LIST'),
  ('TEST', 'Anti-Phospholipid Antibody (APLA)-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 650, 0, 650, 450, '', 'RATE_LIST'),
  ('TEST', 'Anti- Saccharomyces Cerevisiae Antibody (ASCA) - IgA', 'EIA', 'Serum', '2 ml', 'Tue', '1 pm', '4th Day', 1500, 0, 1500, 1200, '', 'RATE_LIST'),
  ('TEST', 'Anti- Saccharomyces Cerevisiae Antibody (ASCA) - IgG', 'EIA', 'Serum', '2 ml', 'Tue', '1 pm', '4th Day', 1500, 0, 1500, 1200, '', 'RATE_LIST'),
  ('TEST', 'Anti-Smooth Muscle Antibody (ASMA)', 'IFA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1400, 0, 1400, 1200, '', 'RATE_LIST'),
  ('TEST', 'Anti-Sperm Antibodies', 'ELISA', 'Serum', '2 ml', 'Mon, Wed, Fri', '1 pm', '3rd Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Anti-Thrombin III Activity', 'Chromogenic Assay', 'Citrate Plasma', '2 ml', 'Daily', '1 pm', '3rd Day', 2000, 0, 2000, 1500, '', 'RATE_LIST'),
  ('TEST', 'Anti-Thyroglobulin Antibody (ATG/ATA)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 600, 0, 600, 400, '', 'RATE_LIST'),
  ('TEST', 'Anti-Thyroid Antibodies (ATPO & ATG)', 'CLIA', 'Serum', '3 ml', 'Daily', '1 pm', 'Same Day', 1100, 0, 1100, 900, '', 'RATE_LIST'),
  ('TEST', 'Apolipoprotein A1 (Apo-A1)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 500, 0, 500, 300, '', 'RATE_LIST'),
  ('TEST', 'Apolipoprotein B (Apo-B)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 500, 0, 500, 350, '', 'RATE_LIST'),
  ('TEST', 'APTT (Activated Partial Thromboplastin Time)', 'Coagulation', 'Citrate Plasma', '2 ml', 'Daily', '', 'Same Day', 180, 0, 180, 100, '', 'RATE_LIST'),
  ('TEST', 'APT-Downey (Alkali denaturation) Test', 'Biochemical', 'Fetal Stool', '50 g', 'Daily', '', 'Same Day', 200, 0, 200, 100, '', 'RATE_LIST'),
  ('TEST', 'ASO (Anti-Streptolysin O)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 250, 0, 250, 120, '', 'RATE_LIST'),
  ('TEST', 'ASO (Anti-Streptolysin O)-Latex', 'Latex Agglutination', 'Serum', '2 ml', 'Daily', '', 'Same Day', 150, 0, 150, 50, '', 'RATE_LIST'),
  ('TEST', 'Aspergillus Antibodies- IgG& IgM', 'EIA', 'Serum', '2 ml', 'Mon, Wed', '1 pm', '3rd Day', 3500, 0, 3500, 2800, '', 'RATE_LIST'),
  ('TEST', 'Aspergillus Antibody-IgG', 'EIA', 'Serum', '2 ml', 'Mon, Wed, Sat', '1 pm', '3rd Day', 2000, 0, 2000, 1600, '', 'RATE_LIST'),
  ('TEST', 'Aspergillus Antibody-IgM', 'EIA', 'Serum', '2 ml', 'Mon, Wed', '1 pm', '3rd Day', 2000, 0, 2000, 1600, '', 'RATE_LIST'),
  ('TEST', 'Aspergillus Specific IgE (A. fumigates Allergen)', 'Immunocap', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1300, 0, 1300, 1100, '', 'RATE_LIST'),
  ('TEST', 'Barbiturates', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Benzodiazephine', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Bence Jones Proteins (BJP)', 'Chemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 100, 0, 100, 60, '', 'RATE_LIST'),
  ('TEST', 'Beta 2-Glycoprotein 1 Panel-IgG, IgM & IgA', 'EIA', 'Serum', '2 ml', 'Tue, Sat', '1 pm', '3rd Day', 2700, 0, 2700, 2300, '', 'RATE_LIST'),
  ('TEST', 'Beta 2-Glycoprotein 1-IgG', 'EIA', 'Serum', '2 ml', 'Tue, Sat', '1 pm', '3rd Day', 1100, 0, 1100, 900, '', 'RATE_LIST'),
  ('TEST', 'Beta 2-Glycoprotein 1-IgM', 'EIA', 'Serum', '2 ml', 'Tue, Sat', '1 pm', '3rd Day', 1100, 0, 1100, 900, '', 'RATE_LIST'),
  ('TEST', 'Beta 2-Microglobulin', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1400, 0, 1400, 1150, '', 'RATE_LIST'),
  ('TEST', 'Beta HCG-Total', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 450, 0, 450, 250, '', 'RATE_LIST'),
  ('TEST', 'Bicarbonate', 'Calculated', 'Serum', '2 ml', 'Daily', '', 'Same Day', 120, 0, 120, 80, '', 'RATE_LIST'),
  ('TEST', 'Bile Acids-Total', 'Biochemical', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1600, 0, 1600, 1300, '', 'RATE_LIST'),
  ('TEST', 'Bile Pigment', 'Chemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 30, 0, 30, 20, '', 'RATE_LIST'),
  ('TEST', 'Bile Salt', 'Chemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 30, 0, 30, 20, '', 'RATE_LIST'),
  ('TEST', 'Bilirubin-Direct', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 50, 0, 50, 40, '', 'RATE_LIST'),
  ('TEST', 'Bilirubin-Total', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 50, 0, 50, 40, '', 'RATE_LIST'),
  ('TEST', 'Bilirubin-Total, Direct & Indirect', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 60, 0, 60, 40, '', 'RATE_LIST'),
  ('TEST', 'Biotinidase- Quantitative', 'EIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 3800, 0, 3800, 3300, '', 'RATE_LIST'),
  ('TEST', 'Blood Group', 'ABO & Rh/ IgG Blend', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 20, 0, 20, 15, '', 'RATE_LIST'),
  ('TEST', 'BNP (B-Type Natriuretic Peptide)', 'CLIA', 'EDTA Plasma', '2 ml', 'Daily', '1 pm', '3rd Day', 2000, 0, 2000, 1500, '', 'RATE_LIST'),
  ('TEST', 'Brucella antibody-IgG', 'EIA', 'Serum', '2 ml', 'Mon, Wed, Fri', '1 pm', '3rd Day', 800, 0, 800, 700, '', 'RATE_LIST'),
  ('TEST', 'Brucella antibody-IgM', 'EIA', 'Serum', '2 ml', 'Mon, Wed, Fri', '1 pm', '3rd Day', 800, 0, 800, 700, '', 'RATE_LIST'),
  ('TEST', 'Brucella Screening', 'Agglutination', 'Serum', '2 ml', 'Daily', '', 'Same Day', 600, 0, 600, 450, '', 'RATE_LIST'),
  ('TEST', 'BUN (Blood Urea Nitrogen)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 150, '', 'RATE_LIST')
) AS v(test_type, name, method, sample, volume, scheduled_days, cut_of_time,
       reporting_time, rate, discount_percent, amount, lab_rate, internal_note, source)
ON CONFLICT ((lower(name))) DO NOTHING;

INSERT INTO app.lab_test
  (test_type, name, method, sample, volume, scheduled_days, cut_of_time,
   reporting_time, rate, discount_percent, amount, lab_rate, internal_note,
   source, created_by, updated_by)
SELECT v.*, 'Rate list import', 'Rate list import'
FROM (VALUES
  ('TEST', 'BUN/Creatinine Ratio', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 250, '', 'RATE_LIST'),
  ('TEST', 'C3 (Complement 3)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 450, 0, 450, 350, '', 'RATE_LIST'),
  ('TEST', 'C4 (Complement 4)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 600, 0, 600, 450, '', 'RATE_LIST'),
  ('TEST', 'CA-125 (Ovarian Cancer Marker)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 800, 0, 800, 500, '', 'RATE_LIST'),
  ('TEST', 'CA-15.3 (Breast Cancer Marker)', 'CMIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 800, 0, 800, 600, '', 'RATE_LIST'),
  ('TEST', 'CA-19.9 (Pancreatic Cancer Marker)', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 850, 0, 850, 600, '', 'RATE_LIST'),
  ('TEST', 'CA-72.4 (Gastric Cancer Marker)', 'Electrochemiluminescence', 'Serum', '2 ml', 'Tue, Sat', '1 pm', '3rd Day', 1700, 0, 1700, 1400, '', 'RATE_LIST'),
  ('TEST', 'Calcitonin', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '5th Day', 1700, 0, 1700, 1400, '', 'RATE_LIST'),
  ('TEST', 'Calcium/Creatinine Ratio-Urine (24 hrs)', 'Biochemical', '24 hrs Urine', '20 ml', 'Daily', '', 'Same Day', 250, 0, 250, 180, '', 'RATE_LIST'),
  ('TEST', 'Calcium/Creatinine Ratio-Urine (Spot)', 'Biochemical', 'Urine', '20 ml', 'Daily', '', 'Same Day', 250, 0, 250, 150, '', 'RATE_LIST'),
  ('TEST', 'Calcium-Serum', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 80, 0, 80, 40, '', 'RATE_LIST'),
  ('TEST', 'Calcium-Urine (24 hrs)', 'Biochemical', '24 hrs Urine', '', 'Daily', '', 'Same Day', 150, 0, 150, 100, '', 'RATE_LIST'),
  ('TEST', 'Calcium-Urine (Spot)', 'Biochemical', 'Urine', '20 ml', 'Daily', '', 'Same Day', 100, 0, 100, 80, '', 'RATE_LIST'),
  ('TEST', 'Calprotectin-Fecal', 'CLIA', 'Stool', '100 g', 'Daily', '1 pm', '4th Day', 2750, 0, 2750, 2400, '', 'RATE_LIST'),
  ('TEST', 'Cannabinoids-Marijuana, THC', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Carbamazepine-Tegretol', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 650, 0, 650, 500, '', 'RATE_LIST'),
  ('TEST', 'Catecholamine-Plasma', 'EIA', 'EDTA Plasma', '2 ml', 'Mon', '1 pm', '4th Day', 6000, 0, 6000, 5400, '', 'RATE_LIST'),
  ('TEST', 'Catecholamine-Urine (24 hrs)', 'LC-MS/MS', 'Urine', '50 ml', 'Mon, Thu', '1 pm', '4th Day', 4500, 0, 4500, 4000, '', 'RATE_LIST'),
  ('TEST', 'Catecholamine-Urine (Spot)', 'LC-MS/MS', 'Urine', '50 ml', 'Mon, Thu', '1 pm', '4th Day', 4500, 0, 4500, 4000, '', 'RATE_LIST'),
  ('TEST', 'CBC (Complete Haemogram)', 'Automated', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 100, '', 'RATE_LIST'),
  ('TEST', 'CD 19', 'Flow Cytometry', 'EDTA & Sod. Heparin Blood', '2 ml', 'Daily', '1 pm', '3rd Day', 2000, 0, 2000, 1700, '', 'RATE_LIST'),
  ('TEST', 'CD4', 'Flow Cytometry', 'EDTA Blood', '2 ml', 'Daily', '1 pm', '4th Day', 1700, 0, 1700, 1400, '', 'RATE_LIST'),
  ('TEST', 'CD3, CD4, CD8, CD45 counts', 'Flow Cytometry', 'EDTA Blood', '2 ml', 'Daily', '1 pm', '4th Day', 1700, 0, 1700, 1400, '', 'RATE_LIST'),
  ('TEST', 'CEA (Carcinoembryonic Antigen)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 550, 0, 550, 350, '', 'RATE_LIST'),
  ('TEST', 'Ceruloplasmin', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 800, 0, 800, 650, '', 'RATE_LIST'),
  ('TEST', 'Chikungunya Detection', 'RT PCR', 'EDTA Blood', '3 ml', 'Daily', '1 pm', '4th Day', 2000, 0, 2000, 1500, '', 'RATE_LIST'),
  ('TEST', 'Chikungunya Screening-IgM', 'IC', 'Serum', '2 ml', 'Daily', '', 'Same Day', 800, 0, 800, 600, '', 'RATE_LIST'),
  ('TEST', 'Chlamydia trachomatis Antibody-IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1200, 0, 1200, 850, '', 'RATE_LIST'),
  ('TEST', 'Chlamydia trachomatis Antibody-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1200, 0, 1200, 850, '', 'RATE_LIST'),
  ('TEST', 'Chloride-Serum', 'ISE', 'Serum', '2 ml', 'Daily', '', 'Same Day', 80, 0, 80, 40, '', 'RATE_LIST'),
  ('TEST', 'Chloride-Urine (24 hrs)', 'ISE', '24 hrs Urine', '10 ml', 'Daily', '', 'Same Day', 150, 0, 150, 100, '', 'RATE_LIST'),
  ('TEST', 'Chloride-Urine (Spot)', 'ISE', 'Urine', '10 ml', 'Daily', '', 'Same Day', 120, 0, 120, 90, '', 'RATE_LIST'),
  ('TEST', 'Cholesterol-HDL', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 120, 0, 120, 90, '', 'RATE_LIST'),
  ('TEST', 'Cholesterol-LDL', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 150, 0, 150, 100, '', 'RATE_LIST'),
  ('TEST', 'Cholesterol-Total', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 50, 0, 50, 40, '', 'RATE_LIST'),
  ('TEST', 'Cholinesterase (Pseudocholinesterase)', 'Biochemical', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 800, 0, 800, 600, '', 'RATE_LIST'),
  ('TEST', 'Chromogranin-A', 'Trace Method', 'EDTA Plasma', '2 ml', 'Wed, Sat', '1 pm', '3rd Day', 4500, 0, 4500, 4000, '', 'RATE_LIST'),
  ('TEST', 'Chylomicron', 'Microscopy', 'Urine', '10 ml', 'Daily', '1 pm', '4th Day', 600, 0, 600, 450, '', 'RATE_LIST'),
  ('TEST', 'Citrate-Urine (24 hrs)', 'Biochemical', '24 hrs Urine', '10 ml', 'Daily', '1 pm', '4th Day', 900, 0, 900, 700, '', 'RATE_LIST'),
  ('TEST', 'CK-MB (Creatine Kinase)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 200, '', 'RATE_LIST'),
  ('TEST', 'Clostridium difficile Detection', 'CLIA', 'Stool', '50 g', 'Daily', '1 pm', '3rd Day', 2800, 0, 2800, 2300, '', 'RATE_LIST'),
  ('TEST', 'Clot Retraction Time', 'Manual', 'Blood', '5 ml', 'Daily', '', '', 0, 0, 0, 100, '', 'RATE_LIST'),
  ('TEST', 'CMV (Cytomegalovirus)-IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 450, 0, 450, 300, '', 'RATE_LIST'),
  ('TEST', 'CMV (Cytomegalovirus)-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 450, 0, 450, 300, '', 'RATE_LIST'),
  ('TEST', 'CMV (Cytomegalovirus)-Qualitative PCR', 'PCR', 'All Body Fluids', '5 ml', 'Daily', '1 pm', '4th Day', 3900, 0, 3900, 3400, '', 'RATE_LIST'),
  ('TEST', 'CMV (Cytomegalovirus)- DNA Quantitative PCR', 'RT PCR', 'EDTA Plasma', '2 ml', 'Daily', '1 pm', '4th Day', 8000, 0, 8000, 7000, '', 'RATE_LIST'),
  ('TEST', 'Cocaine', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Coomb’s Test-Direct (DCT)', 'Tube Method', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 300, 0, 300, 200, '', 'RATE_LIST'),
  ('TEST', 'Coomb’s Test-Indirect (ICT)', 'Tube Method', 'Serum', '2 ml', 'Daily', '', 'Same Day', 250, 0, 250, 100, '', 'RATE_LIST'),
  ('TEST', 'Copper-Serum', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 400, 0, 400, 200, '', 'RATE_LIST'),
  ('TEST', 'Copper-Urine (24 hrs)', 'ICPMS', '24 hrs Urine', '10 ml', 'Daily', '1 pm', '4th Day', 1700, 0, 1700, 1500, '', 'RATE_LIST'),
  ('TEST', 'Copper-Urine (spot)', 'ICPMS', 'Urine', '10 ml', 'Daily', '1 pm', '4th Day', 1700, 0, 1700, 1500, '', 'RATE_LIST'),
  ('TEST', 'Cortisol-Serum (8 AM or 4 PM)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 450, 0, 450, 300, '', 'RATE_LIST'),
  ('TEST', 'Cortisol Free -Urine (24 hrs)', 'CLIA', '24 hrs Urine', '10 ml', 'Daily', '', 'Same Day', 800, 0, 800, 500, '', 'RATE_LIST'),
  ('TEST', 'C-peptide', 'ELISA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 600, 0, 600, 450, '', 'RATE_LIST'),
  ('TEST', 'CPK (Creatinine Phosphokinase)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 250, 0, 250, 100, '', 'RATE_LIST'),
  ('TEST', 'Creatinine Clearance Test', 'Biochemical', 'Serum + 24 hrs Urine(10ml)', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 150, '', 'RATE_LIST'),
  ('TEST', 'Creatinine-Serum', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 70, 0, 70, 40, '', 'RATE_LIST'),
  ('TEST', 'Creatinine-Urine (24 hrs)', 'Biochemical', '24 hrs Urine', '10 ml', 'Daily', '', 'Same Day', 100, 0, 100, 80, '', 'RATE_LIST'),
  ('TEST', 'Creatinine-Urine (Spot)', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 60, 0, 60, 40, '', 'RATE_LIST'),
  ('TEST', 'CRP (C-Reactive Protein)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'CRP (C-Reactive Protein)-Latex', 'Latex Agglutination', 'Serum', '2 ml', 'Daily', '', 'Same Day', 150, 0, 150, 50, '', 'RATE_LIST'),
  ('TEST', 'CRP-hs (High Sensitive)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 550, 0, 550, 300, '', 'RATE_LIST'),
  ('TEST', 'Cryoglobulins-Qualitative', 'Precipitation Method', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 400, 0, 400, 250, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-AFB', 'Culture', 'Sputum/Urine/Body Fluids', '', 'Daily', '', '45th Day', 500, 0, 500, 350, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Blood', 'Culture', 'Blood', '', 'Daily', '', '3rd Day (1st report)', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Body Fluids', 'Culture', 'Body Fluids', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Bronchial Wash', 'Culture', 'Swab', '', 'Daily', '', '3rd Day', 300, 0, 300, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Catheter Tips', 'Culture', 'Swab', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Conjunctival Swab', 'Culture', 'Swab', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-CSF', 'Culture', 'CSF', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Dialysis Fluids', 'Culture', 'Dialysis Fluids', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Ear Swab', 'Culture', 'Swab', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Fungal', 'Culture', 'Swab', '', 'Daily', '', '7th Day', 450, 0, 450, 250, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Motion', 'Culture', 'Stool', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-MRSA', 'Culture', 'Swab', '', 'Daily', '', '3rd Day', 300, 0, 300, 200, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Nasal Swab', 'Culture', 'Swab', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Pleural Fluid', 'Culture', 'Swab', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Pus', 'Culture', 'Pus', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Semen', 'Culture', 'Semen', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Sputum', 'Culture', 'Sputum', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Throat Swab', 'Culture', 'Swab', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Culture & Sensitivity-Urine', 'Culture', 'Urine', '', 'Daily', '', '3rd Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Cystatin-C', 'Nephelometry', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 1100, 0, 1100, 900, '', 'RATE_LIST'),
  ('TEST', 'D-Dimer-Quantitative', 'Nephelometry', 'Citrate Plasma', '2 ml', 'Daily', '', 'Same Day', 700, 0, 700, 400, '', 'RATE_LIST'),
  ('TEST', 'Dengue Antibody-IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 600, 0, 600, 450, '', 'RATE_LIST'),
  ('TEST', 'Dengue Antibody-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 600, 0, 600, 450, '', 'RATE_LIST'),
  ('TEST', 'Dengue NS1 Antigen', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 800, 0, 800, 650, '', 'RATE_LIST'),
  ('TEST', 'Dengue NS1 Antigen Screening', 'IC', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 280, '', 'RATE_LIST'),
  ('TEST', 'Dengue NS1, IgG & IgM', 'IC', 'Serum', '2 ml', 'Daily', '', 'Same Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'DHEA (Dehydroepiandrosterone)', 'EIA', 'Serum', '2 ml', 'Wed, Sat', '1 pm', '3rd Day', 2500, 0, 2500, 2200, '', 'RATE_LIST'),
  ('TEST', 'DHEA-S (Dehydroepiandrosterone-sulfate)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 600, 0, 600, 400, '', 'RATE_LIST'),
  ('TEST', 'Differential Count-WBC', 'Automated/Manual', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 30, 0, 30, 20, '', 'RATE_LIST'),
  ('TEST', 'Digoxin (Lanoxin)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 900, 0, 900, 750, '', 'RATE_LIST'),
  ('TEST', 'Dihydrotestosterone (DHT)', 'EIA', 'Serum', '2 ml', 'Tue', '1 pm', '3rd Day', 2500, 0, 2500, 2200, '', 'RATE_LIST'),
  ('TEST', 'Downey test (Alkali denaturation test)', 'Manual', 'Stool', '50 g', 'Daily', '', 'Same Day', 250, 0, 250, 150, '', 'RATE_LIST'),
  ('TEST', 'DPD Gene Mutation (5-FU toxicity)', 'RTPCR', 'EDTA Blood', '5 ml', 'Daily', '1 pm', '14th Day', 7500, 0, 7500, 6700, '', 'RATE_LIST'),
  ('TEST', 'Drugs of Abuse Panel-6 Drugs', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 2000, 0, 2000, 1200, '', 'RATE_LIST'),
  ('TEST', 'Drugs of Abuse Panel-9 Drugs', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 2700, 0, 2700, 1800, '', 'RATE_LIST'),
  ('TEST', 'Drugs of Abuse Panel-11 Drugs', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 3500, 0, 3500, 2400, '', 'RATE_LIST')
) AS v(test_type, name, method, sample, volume, scheduled_days, cut_of_time,
       reporting_time, rate, discount_percent, amount, lab_rate, internal_note, source)
ON CONFLICT ((lower(name))) DO NOTHING;

INSERT INTO app.lab_test
  (test_type, name, method, sample, volume, scheduled_days, cut_of_time,
   reporting_time, rate, discount_percent, amount, lab_rate, internal_note,
   source, created_by, updated_by)
SELECT v.*, 'Rate list import', 'Rate list import'
FROM (VALUES
  ('TEST', 'Dysmorphic RBC-Urine', 'Phase Contrast Microscopy', 'Urine', '10 ml', 'Daily', '', 'Next Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'E2 (Estradiol)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 550, 0, 550, 350, '', 'RATE_LIST'),
  ('TEST', 'EGFR (Estimated Glomerular Filtration Rate)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 150, '', 'RATE_LIST'),
  ('TEST', 'Electrolytes-2 (Na+, K+)', 'ISE', 'Serum/Urine (10 ml)', '2 ml', 'Daily', '', 'Same Day', 180, 0, 180, 100, '', 'RATE_LIST'),
  ('TEST', 'Electrolytes-4 (Na+, K+, Cl-, HCO-3)', 'ISE', 'Serum/Urine (10 ml)', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 250, '', 'RATE_LIST'),
  ('TEST', 'ENA Profile', 'Immunoblot (LIA)', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 3000, 0, 3000, 2000, '', 'RATE_LIST'),
  ('TEST', 'Eosinophils', 'Microscopy', 'Sputum/ Urine', '10 ml', 'Daily', '', 'Same Day', 100, 0, 100, 50, '', 'RATE_LIST'),
  ('TEST', 'Epstein Barr Virus (EBV)-IgG', 'EIA', 'Serum', '2 ml', 'Mon, Thu', '1 pm', '3rd Day', 2000, 0, 2000, 1800, '', 'RATE_LIST'),
  ('TEST', 'Epstein Barr Virus (EBV)-IgM', 'EIA', 'Serum', '2 ml', 'Mon, Thu', '1 pm', '3rd Day', 2000, 0, 2000, 1800, '', 'RATE_LIST'),
  ('TEST', 'Erythropoietin Level', 'CLIA', 'Serum', '2 ml', 'Tue, Sat', '1 pm', '3rd Day', 1600, 0, 1600, 1200, '', 'RATE_LIST'),
  ('TEST', 'Erythrocyte Sedimentation Rate (ESR)', 'Manual', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 30, 0, 30, 20, '', 'RATE_LIST'),
  ('TEST', 'Estriol (E3)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 800, 0, 800, 600, '', 'RATE_LIST'),
  ('TEST', 'Factor V Leiden (Functional)', 'Clot Detection', 'Citrate Plasma', '2 ml', 'Tue', '1 pm', '4th Day', 3000, 0, 3000, 2000, '', 'RATE_LIST'),
  ('TEST', 'Factor V Leiden (Mutation Analysis)', 'RT PCR', 'EDTA Blood', '2 ml', 'Tue, Sat', '1 pm', '5th Day', 4500, 0, 4500, 4000, '', 'RATE_LIST'),
  ('TEST', 'Factor X Activity (Functional)', 'Clot Detection', 'Citrate Plasma', '2 ml', 'Tue', '1 pm', '4th Day', 4500, 0, 4500, 3900, '', 'RATE_LIST'),
  ('TEST', 'Fat Globules', 'Microscopy', 'Urine/Motion (50g)', '10 ml', 'Daily', '', 'Same Day', 100, 0, 100, 50, '', 'RATE_LIST'),
  ('TEST', 'Ferritin', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 450, 0, 450, 280, '', 'RATE_LIST'),
  ('TEST', 'Fibrinogen Degradation Product (FDP)', 'Agglutination', 'Sodium Citrate Plasma', '3 ml', 'Daily', '1 pm', '3rd Day', 1000, 0, 1000, 800, '', 'RATE_LIST'),
  ('TEST', 'Fibrinogen Level (Clotting Activity)', 'Clot Detection', 'Sodium Citrate Plasma', '2 ml', 'Daily', '1 pm', '3rd Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Filaria Antibody', 'Immunochromatography', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1300, 0, 1300, 1000, '', 'RATE_LIST'),
  ('TEST', 'Filaria Antigen', 'Immunochromatography', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 700, 0, 700, 600, '', 'RATE_LIST'),
  ('TEST', 'Fluid Analysis', 'Biochemical, Microscopy', 'Body Fluids', '5 ml', 'Daily', '', 'Same Day', 350, 0, 350, 250, '', 'RATE_LIST'),
  ('TEST', 'Fluid for Cytology', 'Microscopy', 'Body Fluids', '5 ml', 'Daily', '', '4th Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'Fluorescent Treponemal Antibody (FTA-Abs)', 'IFA', 'Serum', '2 ml', 'Wed, Sat', '1 pm', '4th Day', 2000, 0, 2000, 1700, '', 'RATE_LIST'),
  ('TEST', 'FNAC (Fine Needle Aspiration Cytology)', 'Microscopy', 'Smear', '', 'Daily', '', '4th Day', 350, 0, 350, 280, '', 'RATE_LIST'),
  ('TEST', 'Food Intolerance Test-IgG', 'Protein Microarray', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 15000, 0, 15000, 12000, '', 'RATE_LIST'),
  ('TEST', 'Fructose-Semen', 'Biochemical', 'Semen', '', 'Daily', '', 'Same Day', 250, 0, 250, 150, '', 'RATE_LIST'),
  ('TEST', 'FSH (Follicle Stimulating Hormone)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 400, 0, 400, 200, '', 'RATE_LIST'),
  ('TEST', 'FT3 (Free Triiodothyronine)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 100, '', 'RATE_LIST'),
  ('TEST', 'FT3, FT4', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 400, 0, 400, 200, '', 'RATE_LIST'),
  ('TEST', 'FT3, FT4, TSH-(Free TFT)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 550, 0, 550, 260, '', 'RATE_LIST'),
  ('TEST', 'FT3, TSH', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 160, '', 'RATE_LIST'),
  ('TEST', 'FT4 (Free Thyroxine)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 100, '', 'RATE_LIST'),
  ('TEST', 'FT4, TSH', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 160, '', 'RATE_LIST'),
  ('TEST', 'Fungal Examination-KOH Test', 'Microscopy', 'Skin Scrapings', '', 'Daily', '', 'Same Day', 200, 0, 200, 100, '', 'RATE_LIST'),
  ('TEST', 'G6PD-Quantitative', 'Biochemical', 'EDTA Blood', '2 ml', 'Daily', '1 pm', 'Same Day', 700, 0, 700, 550, '', 'RATE_LIST'),
  ('TEST', 'GAD-65 antibody (Paraneoplastic Syndrome)', 'IFA', 'Serum', '3 ml', 'Mon', '1 pm', '10th Day', 6500, 0, 6500, 6000, '', 'RATE_LIST'),
  ('TEST', 'GAD-65 antibody (Type I Diabetes)', 'EIA', 'Serum', '2 ml', 'Mon, Thu', '1 pm', '3rd Day', 4000, 0, 4000, 3500, '', 'RATE_LIST'),
  ('TEST', 'Gamma GT (GGT)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 220, 0, 220, 130, '', 'RATE_LIST'),
  ('TEST', 'Gastrin', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1300, 0, 1300, 1050, '', 'RATE_LIST'),
  ('TEST', 'GCT (Glucose Challenge Test)', 'Biochemical', '', '', 'Daily', '', 'Same Day', 60, 0, 60, 30, '', 'RATE_LIST'),
  ('TEST', 'Glucose (Blood Sugar)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 20, 0, 20, 15, '', 'RATE_LIST'),
  ('TEST', 'Gram Stain', 'Staining & Microscopy', 'Any Body Fluids', '', 'Daily', '', 'Same Day', 150, 0, 150, 80, '', 'RATE_LIST'),
  ('TEST', 'Growth Hormone (GH)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 600, 0, 600, 400, '', 'RATE_LIST'),
  ('TEST', 'Growth Hormone-Releasing Hormone', 'CLIA', 'Serum', '3 ml', 'Daily', '1 pm', '3rd Day', 3000, 0, 3000, 2700, '', 'RATE_LIST'),
  ('TEST', 'GTT (Glucose Tolerance Test)', 'Biochemical', '', '', 'Daily', '', 'Same Day', 120, 0, 120, 80, '', 'RATE_LIST'),
  ('TEST', 'Haemoglobin (Hb)', 'Automated', 'EDTA Blood', '2 ml', 'Daily', '', '3rd Day', 20, 0, 20, 15, '', 'RATE_LIST'),
  ('TEST', 'Haptoglobin', 'Immunoturbidimetry', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 2000, 0, 2000, 1500, '', 'RATE_LIST'),
  ('TEST', 'Hb Electrophoresis', 'HPLC', 'EDTA Blood', '2 ml', 'Daily', '1 pm', '4th Day', 950, 0, 950, 750, '', 'RATE_LIST'),
  ('TEST', 'HbA1C-HPLC', 'HPLC', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 500, 0, 500, 350, '', 'RATE_LIST'),
  ('TEST', 'HbA1C-Nephelometry', 'Nephelometry', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 300, 0, 300, 200, '', 'RATE_LIST'),
  ('TEST', 'Helicobacter pylori Antigen', 'IC', 'Stool', '50 gms', 'Daily', '', 'Same Day', 1200, 0, 1200, 800, '', 'RATE_LIST'),
  ('TEST', 'Helicobacter pylori-IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1000, 0, 1000, 750, '', 'RATE_LIST'),
  ('TEST', 'Helicobacter pylori-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1000, 0, 1000, 750, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis A Virus (Anti-HAV)-IgG', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 800, 0, 800, 700, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis A Virus (Anti-HAV)-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 650, 0, 650, 400, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Core Antibody (Anti-HBc)-IgM', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 600, 0, 600, 450, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Core Antibody (Anti-HBc)-Total', 'ELISA/ELFA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 700, 0, 700, 550, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Core Antigen (HBcAg)', 'CMIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 700, 0, 700, 600, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Envelop Antibody (Anti-HBe)', 'CMIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 650, 0, 650, 500, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Envelop Antigen (HBeAg)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 650, 0, 650, 500, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Surface Antibody (Anti-HBsTiter)', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 600, 0, 600, 400, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Surface Antigen (HBsAg)-CLIA', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 500, 0, 500, 450, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Surface Antigen (HBsAg)-CMIA', 'CMIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Surface Antigen (HBsAg)-ECLIA', 'ECLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Surface Antigen (HBsAg)-ELFA', 'ELFA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Surface Antigen (HBsAg)-ELISA', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 300, 0, 300, 170, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Surface Antigen (HBsAg)-Screening', 'IC', 'Serum', '2 ml', 'Daily', '', 'Same Day', 100, 0, 100, 70, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Virus (HBV) DNA Qualitative PCR', 'RT PCR', 'EDTA plasma', '2 ml', 'Daily', '1 pm', 'Next Day', 3000, 0, 3000, 2200, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis B Virus (HBV) DNA Quantitative PCR', 'RT PCR', 'EDTA plasma', '2 ml', 'Daily', '1 pm', 'Next Day', 4800, 0, 4800, 4000, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis C Virus (Anti-HCV)-CLIA', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 700, 0, 700, 550, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis C Virus (Anti-HCV)-CMIA', 'CMIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 800, 0, 800, 650, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis C Virus (Anti-HCV)-ECLIA', 'ECLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 800, 0, 800, 650, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis C Virus (Anti-HCV)-ELFA', 'ELFA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 800, 0, 800, 650, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis C Virus (Anti-HCV)-ELISA', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 500, 0, 500, 300, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis C Virus (Anti-HCV)-Screening', 'IC', 'Serum', '2 ml', 'Daily', '', 'Same Day', 250, 0, 250, 200, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis C Virus (HCV) RNA Genotyping', 'RT PCR', 'Serum', '2 ml', 'Daily', '1 pm', '1 week', 5000, 0, 5000, 4000, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis C Virus (HCV) RNA Qualitative PCR', 'RT PCR', 'EDTA plasma', '2 ml', 'Daily', '1 pm', 'Next Day', 3000, 0, 3000, 2400, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis C Virus (HCV) RNA Quantitative PCR', 'RT PCR', 'EDTA plasma', '2 ml', 'Daily', '1 pm', 'Next Day', 5000, 0, 5000, 4000, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis E Virus (Anti-HEV)-IgG', 'EIA', 'Serum', '2 ml', 'Tue, Sat', '1 pm', '3rd Day', 1400, 0, 1400, 1200, '', 'RATE_LIST'),
  ('TEST', 'Hepatitis E Virus (Anti-HEV)-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 750, 0, 750, 600, '', 'RATE_LIST'),
  ('TEST', 'Histopathology Biopsy-Large', 'Staining & Microscopy', 'Biopsy', '', 'Daily', '', '10th Day', 1000, 0, 1000, 650, '', 'RATE_LIST'),
  ('TEST', 'Histopathology Biopsy-Medium', 'Staining & Microscopy', 'Biopsy', '', 'Daily', '', '7th Day', 750, 0, 750, 450, '', 'RATE_LIST'),
  ('TEST', 'Histopathology Biopsy-Small', 'Staining & Microscopy', 'Biopsy', '', 'Daily', '', '7th Day', 500, 0, 500, 350, '', 'RATE_LIST'),
  ('TEST', 'HIV 1 RNA Quantitative', 'RT PCR', 'EDTA Plasma', '3 ml', 'Daily', '1 pm', '1 week', 5000, 0, 5000, 4300, '', 'RATE_LIST'),
  ('TEST', 'HIV 1&2 Antibodies-CMIA', 'CMIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 500, 0, 500, 400, '', 'RATE_LIST'),
  ('TEST', 'HIV 1&2 Antibodies-ECLIA', 'ECLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 500, 0, 500, 400, '', 'RATE_LIST'),
  ('TEST', 'HIV 1&2 Antibodies-ELFA', 'ELFA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 500, 0, 500, 400, '', 'RATE_LIST'),
  ('TEST', 'HIV 1&2 Antibodies-ELISA', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 300, 0, 300, 150, '', 'RATE_LIST'),
  ('TEST', 'HIV 1&2 Antibodies-Screening', 'IC', 'Serum', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'HIV 1&2 Antibodies-Western Blot', 'Western Blot', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 2000, 0, 2000, 1600, '', 'RATE_LIST'),
  ('TEST', 'HIV 2 RNA Quantitative', 'RT PCR', 'EDTA Plasma', '3 ml', 'Daily', '1 pm', '1 week', 4500, 0, 4500, 3800, '', 'RATE_LIST'),
  ('TEST', 'HIV DUO (p24 Antigen & HIV1 &2 Antibody)', 'CMIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 800, 0, 800, 600, '', 'RATE_LIST'),
  ('TEST', 'HIV P 24 Antigen', 'ELFA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 1000, 0, 1000, 800, '', 'RATE_LIST'),
  ('TEST', 'HLA B27 (Qualitative PCR)', 'RT PCR', 'EDTA Blood', '4 ml', 'Daily', '1 pm', 'Next Day', 3000, 0, 3000, 2500, '', 'RATE_LIST'),
  ('TEST', 'HLA B5 (B51/52)', 'PCR-SSOP-Luminex', 'EDTA Blood', '4 ml', 'Daily', '1 pm', '4th Day', 4500, 0, 4500, 3800, '', 'RATE_LIST'),
  ('TEST', 'HLAB27 (Flow Cytometry)', 'Flow Cytometry', 'EDTA Blood', '4 ml', 'Daily', '1 pm', '4th Day', 1500, 0, 1500, 1100, '', 'RATE_LIST'),
  ('TEST', 'Homocysteine', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 900, 0, 900, 700, '', 'RATE_LIST'),
  ('TEST', 'Homogentisic Acid (Alkaptonuria)-Qualitative', 'Chemical', 'Urine', '10 ml', 'Daily', '1 pm', '4th Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'Homogentisic Acid (Alkaptonuria)-Quantitative', 'Biochemical', 'Urine', '10 ml', 'Daily', '1 pm', '5th Day', 900, 0, 900, 750, '', 'RATE_LIST')
) AS v(test_type, name, method, sample, volume, scheduled_days, cut_of_time,
       reporting_time, rate, discount_percent, amount, lab_rate, internal_note, source)
ON CONFLICT ((lower(name))) DO NOTHING;

INSERT INTO app.lab_test
  (test_type, name, method, sample, volume, scheduled_days, cut_of_time,
   reporting_time, rate, discount_percent, amount, lab_rate, internal_note,
   source, created_by, updated_by)
SELECT v.*, 'Rate list import', 'Rate list import'
FROM (VALUES
  ('TEST', 'HPV (HUMAN PAPILLOMA VIRUS) QUALITATIVE PCR', 'RT PCR', 'Swab', '', 'Mon, Thu', '1 pm', '5th Day', 1300, 0, 1300, 1000, '', 'RATE_LIST'),
  ('TEST', 'HSV 1&2 (Herpes simplex Virus) Qualitative PCR', 'PCR', 'EDTA Plasma', '2 ml', 'Daily', '1 pm', '9th Day', 3800, 0, 3800, 3200, '', 'RATE_LIST'),
  ('TEST', 'HSV 1&2 (Herpes simplex Virus)-IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 500, 0, 500, 350, '', 'RATE_LIST'),
  ('TEST', 'HSV 1&2 (Herpes simplex Virus)-IgG & IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1000, 0, 1000, 700, '', 'RATE_LIST'),
  ('TEST', 'HSV 1&2 (Herpes simplex Virus)-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 500, 0, 500, 350, '', 'RATE_LIST'),
  ('TEST', 'IGF-1 (Somatomedin C)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 2200, 0, 2200, 1900, '', 'RATE_LIST'),
  ('TEST', 'IGFBP-3', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 3200, 0, 3200, 2900, '', 'RATE_LIST'),
  ('TEST', 'IgG4 (IgG Subclass 4)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 5000, 0, 5000, 4600, '', 'RATE_LIST'),
  ('TEST', 'Immuno Fixation-Qualitative', 'Immunoelectrophoresis', 'Serum', '4 ml', 'Daily', '1 pm', '4th Day', 5000, 0, 5000, 4600, '', 'RATE_LIST'),
  ('TEST', 'Immuno Fixation-Quantitative', 'Immunoelectrophoresis, Nephelometry, CLIA', 'Serum', '4 ml', 'Daily', '1 pm', '4th Day', 7000, 0, 7000, 6300, '', 'RATE_LIST'),
  ('TEST', 'Immunoglobulin profile (IgA, IgG, IgM)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 1200, 0, 1200, 950, '', 'RATE_LIST'),
  ('TEST', 'Immunoglobulin-A (IgA)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 450, 0, 450, 350, '', 'RATE_LIST'),
  ('TEST', 'Immunoglobulin-D (IgD)', 'Flow cytometry', 'EDTA Blood', '3 ml', 'Daily', '1 pm', '1 week', 3500, 0, 3500, 3000, '', 'RATE_LIST'),
  ('TEST', 'Immunoglobulin-E (IgE)-Total', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 500, 0, 500, 250, '', 'RATE_LIST'),
  ('TEST', 'Immunoglobulin-G (IgG)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 450, 0, 450, 300, '', 'RATE_LIST'),
  ('TEST', 'Immunoglobulin-M (IgM)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 600, 0, 600, 450, '', 'RATE_LIST'),
  ('TEST', 'Immunohistochemistry (IHC)', 'IHC', 'Slide & Block', '', '', '', '', 0, 0, 0, 0, 'Please contact for more details', 'RATE_LIST'),
  ('TEST', 'Inhibin A', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1000, 0, 1000, 800, '', 'RATE_LIST'),
  ('TEST', 'Inhibin B', 'EIA', 'Serum', '2 ml', 'Fri', '1 pm', '4th Day', 1900, 0, 1900, 1550, '', 'RATE_LIST'),
  ('TEST', 'Insulin', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 500, 0, 500, 300, '', 'RATE_LIST'),
  ('TEST', 'Insulin Antibodies', 'EIA', 'Serum', '2 ml', 'Thu', '1 pm', '3rd Day', 2000, 0, 2000, 1500, '', 'RATE_LIST'),
  ('TEST', 'Insulin Resistance Index (Homa-IR)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 800, 0, 800, 650, '', 'RATE_LIST'),
  ('TEST', 'Insulin Resistance Index (Homa-IR) C- Peptide Model', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 900, 0, 900, 700, '', 'RATE_LIST'),
  ('TEST', 'Intact Parathyroid Hormones (PTH)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 600, 0, 600, 300, '', 'RATE_LIST'),
  ('TEST', 'Interleukin-6 (IL-6)', 'CLIA', 'EDTA Plasma', '2 ml', 'Daily', '', 'Same Day', 2200, 0, 2200, 1500, '', 'RATE_LIST'),
  ('TEST', 'Intrinsic Factor Antibody', 'EIA', 'Serum', '2 ml', 'Fri', '1 pm', '4th Day', 2600, 0, 2600, 2200, '', 'RATE_LIST'),
  ('TEST', 'Ionized Calcium', 'ISE', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 250, '', 'RATE_LIST'),
  ('TEST', 'Iron', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 250, 0, 250, 170, '', 'RATE_LIST'),
  ('TEST', 'Iron Studies (Iron, TIBC, TSA)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 850, 0, 850, 550, '', 'RATE_LIST'),
  ('TEST', 'Islet Antibody', 'Indirect IFA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1900, 0, 1900, 1600, '', 'RATE_LIST'),
  ('TEST', 'JAK 2 Mutation Detection Qualitative', 'RTPCR', 'EDTA Blood', '3 ml', 'Daily', '1 pm', '4th Day', 5000, 0, 5000, 4500, '', 'RATE_LIST'),
  ('TEST', 'JAK 2 EXON 12 Mutation Detection', 'PCR, Fragment Analysis', 'EDTA Blood', '3 ml', 'Daily', '1 pm', '4th Day', 5400, 0, 5400, 4800, '', 'RATE_LIST'),
  ('TEST', 'Kappa/ Lambda Free Light Chain Assay', 'Nephelometry', 'Serum', '3 ml', 'Daily', '1 pm', '4th Day', 5000, 0, 5000, 4000, '', 'RATE_LIST'),
  ('TEST', 'Karyotyping (Chromosome analysis) by G-banding', 'Karyotyping', 'Sod. Heparin blood', '3 ml', 'Daily', '1 pm', '15th Day', 3200, 0, 3200, 2800, '', 'RATE_LIST'),
  ('TEST', 'KRAS Mutation Detection (Codon 12/13)', 'PCR-SNPE', 'Block / FFPES & Slides', '', 'Daily', '1 pm', '14th Day', 6500, 0, 6500, 5800, '', 'RATE_LIST'),
  ('TEST', 'Lactate', 'Biochemical', 'Sod.Fluoride/EDTA Plasma', '2 ml', 'Daily', '', 'Same Day', 800, 0, 800, 600, '', 'RATE_LIST'),
  ('TEST', 'LDH (Lactate Dehydrogenase)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 250, '', 'RATE_LIST'),
  ('TEST', 'LE Cells (Lupus Erythematosus)', 'Microscopy', 'EDTA Blood', '2 ml', 'Daily', '1 pm', '3rd Day', 300, 0, 300, 250, '', 'RATE_LIST'),
  ('TEST', 'Lead-Blood', 'Spectrometry', 'K2EDTA Blood', '2 ml', 'Daily', '1 pm', '4th Day', 1300, 0, 1300, 1000, '', 'RATE_LIST'),
  ('TEST', 'Lead-Urine (24 hrs)', 'ICPMS', 'Urine', '10 ml', 'Daily', '1 pm', '4th Day', 1400, 0, 1400, 1000, '', 'RATE_LIST'),
  ('TEST', 'Lead-Urine (Spot)', 'ICPMS', 'Urine', '10 ml', 'Daily', '1 pm', '4th Day', 1300, 0, 1300, 1000, '', 'RATE_LIST'),
  ('TEST', 'Leptospira Antibody-IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1000, 0, 1000, 900, '', 'RATE_LIST'),
  ('TEST', 'Leptospira Antibody-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Leptospira Screen-IgG & IgM', 'IC', 'Serum', '2 ml', 'Daily', '', 'Same Day', 450, 0, 450, 300, '', 'RATE_LIST'),
  ('TEST', 'LFT (Liver Function Test)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 300, 0, 300, 210, '', 'RATE_LIST'),
  ('TEST', 'LH (Luteinizing Hormone)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 400, 0, 400, 200, '', 'RATE_LIST'),
  ('TEST', 'Lipase', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 400, 0, 400, 250, '', 'RATE_LIST'),
  ('TEST', 'Lipid Profile', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 250, 0, 250, 150, '', 'RATE_LIST'),
  ('TEST', 'Lipoprotein-A (Lp A)', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 650, 0, 650, 500, '', 'RATE_LIST'),
  ('TEST', 'Lithium', 'ISE', 'Serum', '2 ml', 'Daily', '', 'Same Day', 300, 0, 300, 175, '', 'RATE_LIST'),
  ('TEST', 'LKM (Liver Kidney Microsomes) Antibody', 'IFA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 2000, 0, 2000, 1400, '', 'RATE_LIST'),
  ('TEST', 'Lupus Anticoagulant (LAC)', 'Coagulation', 'Citrate Plasma', '2 ml', 'Daily', '', 'Same Day', 1300, 0, 1300, 800, '', 'RATE_LIST'),
  ('TEST', 'Lyme Antibodies- IgG & IgM', 'EIA', 'Serum', '2 ml', 'Thu', '1 pm', '3rd Day', 3300, 0, 3300, 2800, '', 'RATE_LIST'),
  ('TEST', 'Magnesium', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 150, '', 'RATE_LIST'),
  ('TEST', 'Malarial Dual-Antigen (Vivax & Falciparum)', 'ICPMS', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 550, 0, 550, 450, '', 'RATE_LIST'),
  ('TEST', 'Manganese-Blood', 'ICPMS', 'K2 EDTA Blood', '3 ml', 'Daily', '1 pm', '3rd Day', 2000, 0, 2000, 1700, '', 'RATE_LIST'),
  ('TEST', 'Manganese-Urine', 'ICPMS', 'Urine (24 hrs/Spot)', '50 ml', 'Daily', '1 pm', '3rd Day', 2000, 0, 2000, 1700, '', 'RATE_LIST'),
  ('TEST', 'Mantoux Test/ Tuberculin Test', '', 'Only for walk-ins', '', 'Daily', '', 'Same Day', 80, 0, 80, 0, '', 'RATE_LIST'),
  ('TEST', 'Measles (Rubeola) Antibody-IgG', 'EIA', 'Serum', '2 ml', 'Tue, Fri', '1 pm', '3rd Day', 1400, 0, 1400, 1100, '', 'RATE_LIST'),
  ('TEST', 'Measles (Rubeola) Antibody-IgM', 'EIA', 'Serum', '2 ml', 'Tue, Fri', '1 pm', '3rd Day', 1400, 0, 1400, 1100, '', 'RATE_LIST'),
  ('TEST', 'Mercury-Blood', 'ICPMS', 'Serum/ EDTA Blood', '3 ml', 'Daily', '1 pm', '1 week', 3000, 0, 3000, 2700, '', 'RATE_LIST'),
  ('TEST', 'Mercury-Urine', 'ICPMS', 'Urine (Spot/24 hrs)', '50 ml', 'Daily', '1 pm', '3rd Day', 3000, 0, 3000, 2600, '', 'RATE_LIST'),
  ('TEST', 'Metanephrine (Metanephrine free, Normetanephrine & 3-Methoxytyramine)', 'LC-MS/MS', 'EDTA Plasma', '3 ml', 'Mon, Wed', '1 pm', '4th Day', 6000, 0, 6000, 5300, '', 'RATE_LIST'),
  ('TEST', 'Metanephrine-Fractionated (Plasma)', 'EIA', 'EDTA Plasma', '3 ml', 'Mon', '1 pm', '4th Day', 7000, 0, 7000, 6400, '', 'RATE_LIST'),
  ('TEST', 'Metanephrine-Fractionated (Urine)', 'HPLC', '24 hrs/ Spot Urine', '10 ml', 'Mon, Wed', '1 pm', '5th Day', 6000, 0, 6000, 5400, '', 'RATE_LIST'),
  ('TEST', 'Metanephrine-Free', 'ELISA', 'EDTA Plasma', '3 ml', 'Mon', '1 pm', '4th Day', 4000, 0, 4000, 3500, '', 'RATE_LIST'),
  ('TEST', 'Metanephrine-Total', 'ELISA', '24 hrs Urine', '10 ml', 'Wed, Sat', '1 pm', '3rd Day', 2000, 0, 2000, 1600, '', 'RATE_LIST'),
  ('TEST', 'Methamphetamine', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 400, '', 'RATE_LIST'),
  ('TEST', 'Methdone', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 400, '', 'RATE_LIST'),
  ('TEST', 'Microalbumin/Creatinine Ratio-Urine', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 350, 0, 350, 250, '', 'RATE_LIST'),
  ('TEST', 'Microalbumin-Urine (24 hrs)', 'Nephelometry', 'Urine', '10 ml', 'Daily', '', 'Same Day', 300, 0, 300, 200, '', 'RATE_LIST'),
  ('TEST', 'Microalbumin-Urine (Spot)', 'Nephelometry', 'Urine', '10 ml', 'Daily', '', 'Same Day', 250, 0, 250, 200, '', 'RATE_LIST'),
  ('TEST', 'Mitochondrial Antibody (AMA)', 'IFA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 1700, 0, 1700, 1200, '', 'RATE_LIST'),
  ('TEST', 'Mumps Antibody-IgG', 'EIA/CLIA', 'Serum', '2 ml', 'Tue, Fri', '1 pm', '3rd Day', 1600, 0, 1600, 1200, '', 'RATE_LIST'),
  ('TEST', 'Mumps Antibody-IgM', 'EIA', 'Serum', '2 ml', 'Tue, Fri', '1 pm', '3rd Day', 1600, 0, 1600, 1200, '', 'RATE_LIST'),
  ('TEST', 'Mycoplasma pneumoniae-IgG', 'EIA', 'Serum', '2 ml', 'Fri', '1 pm', '4th Day', 2000, 0, 2000, 1700, '', 'RATE_LIST'),
  ('TEST', 'Mycoplasma pneumoniae-IgM', 'EIA', 'Serum', '2 ml', 'Fri', '1 pm', '4th Day', 2000, 0, 2000, 1700, '', 'RATE_LIST'),
  ('TEST', 'Myoglobin', 'CLIA', 'Urine', '10 ml', 'Daily', '1 pm', '4th Day', 1400, 0, 1400, 1200, '', 'RATE_LIST'),
  ('TEST', 'Neuron Specific Enolase (NSE)', 'Electrochemiluminescence', 'Serum', '2 ml', 'Sat', '1 pm', '3rd Day', 3200, 0, 3200, 2800, '', 'RATE_LIST'),
  ('TEST', 'Newborn screen (Inborn Errors of Metabolism)', 'Fluoroimmunoassay, CE', 'Heel prick blood', '', 'Daily', '1 pm', '3rd Day', 2500, 0, 2500, 2000, '', 'RATE_LIST'),
  ('TEST', 'Nicotine (Cotinine)', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'NMDA Receptor Antibody', 'IFA', 'Serum', '2 ml', 'Wed, Sat', '1 pm', '4th Day', 6200, 0, 6200, 5500, '', 'RATE_LIST'),
  ('TEST', 'NT-PRO-BNP (N-Terminal pro B-Type Natriuretic Peptide)', 'ELFA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 3000, 0, 3000, 2500, '', 'RATE_LIST'),
  ('TEST', 'Occult Blood-Motion', 'Chemical', 'Stool', '50 g', 'Daily', '', 'Same Day', 100, 0, 100, 60, '', 'RATE_LIST'),
  ('TEST', 'Occult Blood-Urine', 'Chemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 100, 0, 100, 60, '', 'RATE_LIST'),
  ('TEST', 'Opiates/ Morphine', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Osmolality-Serum', 'Biochemical', 'Serum', '3 ml', 'Daily', '', 'Same Day', 600, 0, 600, 400, '', 'RATE_LIST'),
  ('TEST', 'Osmolality-Urine', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 600, 0, 600, 400, '', 'RATE_LIST'),
  ('TEST', 'Osmotic Fragility/RBC Fragility', 'Manual', 'Sod. Heparin Blood', '3 ml', 'Daily', '1 pm', '3rd Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'Oxalate-Urine (24 hrs)', 'Biochemical', '24 hrs Urine', '10 ml', 'Mon, Thu', '1 pm', '3rd Day', 1600, 0, 1600, 1300, '', 'RATE_LIST'),
  ('TEST', 'Oxalate-Urine (Spot)', 'Biochemical', 'Urine', '10 ml', 'Mon, Thu', '1 pm', '3rd Day', 1600, 0, 1600, 1300, '', 'RATE_LIST'),
  ('TEST', 'Pap Smear', 'Microscopy', 'Fixed Smears', '', 'Daily', '', '3rd Day', 450, 0, 450, 280, '', 'RATE_LIST'),
  ('TEST', 'Parietal Cell Antibody', 'IF', 'Serum', '2 ml', 'Tue, Fri', '1 pm', '4th Day', 2400, 0, 2400, 2000, '', 'RATE_LIST'),
  ('TEST', 'Parvovirus B19 Qualitative PCR', 'RT PCR', 'EDTA Blood', '2 ml', 'Tue, Fri', '1 pm', '5th Day', 2700, 0, 2700, 2200, '', 'RATE_LIST'),
  ('TEST', 'Paternal Screening/ DNA Finger Printing', 'PCR, STR Analysis', 'EDTA Blood', '3 ml', 'Daily', '1 pm', '1 week', 10000, 0, 10000, 9000, '', 'RATE_LIST'),
  ('TEST', 'Paul Bunnel Test/ Infectious Mononucleosis Test', 'IC', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 300, 0, 300, 200, '', 'RATE_LIST'),
  ('TEST', 'PCOD Profile', 'CLIA', 'Serum (Fasting)', '3 ml', 'Daily', '1 pm', 'Same Day', 2300, 0, 2300, 1600, '', 'RATE_LIST'),
  ('TEST', 'PCV (Packed cell volume)/ Hematocrit', 'Automated', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 60, 0, 60, 40, '', 'RATE_LIST'),
  ('TEST', 'Peripheral Smear Examination (PBF)', 'Microscopy', 'EDTA Blood + Spot Smear', '2 ml', 'Daily', '', '2nd Day', 300, 0, 300, 180, '', 'RATE_LIST'),
  ('TEST', 'Phencyclidine', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST')
) AS v(test_type, name, method, sample, volume, scheduled_days, cut_of_time,
       reporting_time, rate, discount_percent, amount, lab_rate, internal_note, source)
ON CONFLICT ((lower(name))) DO NOTHING;

INSERT INTO app.lab_test
  (test_type, name, method, sample, volume, scheduled_days, cut_of_time,
   reporting_time, rate, discount_percent, amount, lab_rate, internal_note,
   source, created_by, updated_by)
SELECT v.*, 'Rate list import', 'Rate list import'
FROM (VALUES
  ('TEST', 'Phenytoin', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 900, 0, 900, 750, '', 'RATE_LIST'),
  ('TEST', 'Phosphorus-Serum', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 100, 0, 100, 60, '', 'RATE_LIST'),
  ('TEST', 'Phosphorus-Urine (24 hrs)', 'Biochemical', 'Urine', '', 'Daily', '', 'Same Day', 100, 0, 100, 80, '', 'RATE_LIST'),
  ('TEST', 'Phosphorus-Urine (Spot)', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 100, 0, 100, 80, '', 'RATE_LIST'),
  ('TEST', 'Platelet Antibodies', 'IFA', 'Serum', '2 ml', 'Sat', '1 pm', 'Wed', 6000, 0, 6000, 5400, '', 'RATE_LIST'),
  ('TEST', 'Platelet Count', 'Automated, Manual', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 50, 0, 50, 40, '', 'RATE_LIST'),
  ('TEST', 'Polarizing Microscopy', 'Polarizing Microscopy', 'Body Fluids', '5 ml', 'Daily', '1 pm', '3rd Day', 900, 0, 900, 600, '', 'RATE_LIST'),
  ('TEST', 'Porphobilinogen', 'Chemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'Potassium-Serum', 'ISE', 'Serum', '2 ml', 'Daily', '', 'Same Day', 100, 0, 100, 50, '', 'RATE_LIST'),
  ('TEST', 'Potassium-Urine (24 hrs)', 'ISE', 'Urine', '10 ml', 'Daily', '', 'Same Day', 150, 0, 150, 100, '', 'RATE_LIST'),
  ('TEST', 'Potassium-Urine (Spot)', 'ISE', 'Urine', '10 ml', 'Daily', '', 'Same Day', 120, 0, 120, 60, '', 'RATE_LIST'),
  ('TEST', 'Prenatal Screening-1 (Double Marker) [Free BHCG, PAPPA]', 'CLIA', 'Serum', '3 ml', 'Daily', '1 pm', '3rd Day', 1600, 0, 1600, 1350, '', 'RATE_LIST'),
  ('TEST', 'Prenatal Screening-2 (Triple Marker) [AFP, UE3, HCG]', 'CLIA', 'Serum', '3 ml', 'Daily', '1 pm', '3rd Day', 1700, 0, 1700, 1400, '', 'RATE_LIST'),
  ('TEST', 'Prenatal Screening (Quadruple Marker) [AFP, UE3, HCG, Inhibin A]', 'CLIA', 'Serum', '3 ml', 'Daily', '1 pm', '4th Day', 3200, 0, 3200, 2800, '', 'RATE_LIST'),
  ('TEST', 'Procalcitonin (PCT)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 2200, 0, 2200, 1600, '', 'RATE_LIST'),
  ('TEST', 'Progesterone', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 500, 0, 500, 300, '', 'RATE_LIST'),
  ('TEST', 'Prolactin', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 400, 0, 400, 200, '', 'RATE_LIST'),
  ('TEST', 'Propoxiphene', 'IC', 'Urine', '5 ml', 'Daily', '', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'Protein C Activity', 'Chromogenic Assay', 'Citrate Plasma', '2 ml', 'Daily', '1 pm', '3rd Day', 3300, 0, 3300, 2500, '', 'RATE_LIST'),
  ('TEST', 'Protein Electrophoresis', 'Electrophoresis', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 550, 0, 550, 400, '', 'RATE_LIST'),
  ('TEST', 'Protein S Activity', 'Clot Detection', 'Citrate Plasma', '2 ml', 'Tue', '1 pm', '4th Day', 3000, 0, 3000, 2200, '', 'RATE_LIST'),
  ('TEST', 'Protein/Creatinine Ratio-Urine (24 hrs)', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 250, 0, 250, 150, '', 'RATE_LIST'),
  ('TEST', 'Protein/Creatinine Ratio-Urine (spot)', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 250, 0, 250, 100, '', 'RATE_LIST'),
  ('TEST', 'Protein-Total', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 80, 0, 80, 60, '', 'RATE_LIST'),
  ('TEST', 'Protein-Urine (24 - hour)', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 150, 0, 150, 100, '', 'RATE_LIST'),
  ('TEST', 'Protein-Urine (Spot)', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 150, 0, 150, 100, '', 'RATE_LIST'),
  ('TEST', 'Prothrombin Time (PT)', 'Clot Detection', 'Citrate Plasma', '2 ml', 'Daily', '', 'Same Day', 150, 0, 150, 80, '', 'RATE_LIST'),
  ('TEST', 'Prothrombin Time (PTINR)', 'Clot Detection', 'Citrate Plasma', '2 ml', 'Daily', '', 'Same Day', 150, 0, 150, 80, '', 'RATE_LIST'),
  ('TEST', 'PSA (Prostate Specific Antigen)-Free', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 850, 0, 850, 650, '', 'RATE_LIST'),
  ('TEST', 'PSA (Prostate Specific Antigen)-Total', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 500, 0, 500, 270, '', 'RATE_LIST'),
  ('TEST', 'Pyruvate', 'Biochemical', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 2500, 0, 2500, 2000, '', 'RATE_LIST'),
  ('TEST', 'RA Factor', 'Nephelometry', 'Serum', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'RA Factor-Latex', 'Latex Agglutination', 'Serum', '2 ml', 'Daily', '', 'Same Day', 150, 0, 150, 50, '', 'RATE_LIST'),
  ('TEST', 'RBC Count', 'Automated', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 50, 0, 50, 40, '', 'RATE_LIST'),
  ('TEST', 'Reducing Substances-Urine', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 150, 0, 150, 60, '', 'RATE_LIST'),
  ('TEST', 'Renin', 'CLIA', 'EDTA Plasma', '2 ml', 'Daily', '1 pm', '4th Day', 3200, 0, 3200, 2800, '', 'RATE_LIST'),
  ('TEST', 'Renin/Aldosterone Ratio', 'CLIA', 'Serum + EDTA Plasma', '2 ml', 'Daily', '1 pm', '5th Day', 4000, 0, 4000, 3500, '', 'RATE_LIST'),
  ('TEST', 'Reticulocyte Count', 'Microscopy', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 150, 0, 150, 80, '', 'RATE_LIST'),
  ('TEST', 'Reticulocyte Production Index', 'Microscopy', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 400, 0, 400, 300, '', 'RATE_LIST'),
  ('TEST', 'RFT (Renal Function Test)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 140, '', 'RATE_LIST'),
  ('TEST', 'Routine Examination-Blood', 'Multiple Methods', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 80, 0, 80, 50, '', 'RATE_LIST'),
  ('TEST', 'Routine Examination-Motion', 'Microscopy, IC', 'Stool', '10 g', 'Daily', '', 'Same Day', 100, 0, 100, 80, '', 'RATE_LIST'),
  ('TEST', 'Routine Examination-Urine', 'Microscopy', 'Urine', '10 ml', 'Daily', '', 'Same Day', 50, 0, 50, 40, '', 'RATE_LIST'),
  ('TEST', 'RPR (Rapid Plasma Reagin)', 'Flocculation', 'Serum', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 120, '', 'RATE_LIST'),
  ('TEST', 'Rubella antibody-IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 450, 0, 450, 250, '', 'RATE_LIST'),
  ('TEST', 'Rubella antibody-IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 450, 0, 450, 250, '', 'RATE_LIST'),
  ('TEST', 'SARS-CoV 2 (Covid 19)- Antigen', 'IC', 'Nasal Swab', '2 ml', 'Daily', '', 'Same Day', 300, 0, 300, 0, '', 'RATE_LIST'),
  ('TEST', 'SARS-CoV 2 (Covid 19)- RT PCR', 'RT PCR', 'Nasal Swab', '', 'Daily', '1 pm', 'Next Day', 500, 0, 500, 500, '', 'RATE_LIST'),
  ('TEST', 'SARS-CoV 2 (Covid 19)- Antibody Total', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 800, 0, 800, 600, '', 'RATE_LIST'),
  ('TEST', 'SARS-CoV 2 (Covid 19- IgG Antibody, Spike Protein)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 800, 0, 800, 600, '', 'RATE_LIST'),
  ('TEST', 'Scrub Typhus-IgM', 'ELISA', 'Serum', '2 ml', 'Wed, Sat', '1 pm', '4th Day', 1200, 0, 1200, 1000, '', 'RATE_LIST'),
  ('TEST', 'Semen Detailed Analysis', 'Manual', 'Semen', '', 'Daily', '', 'Same Day', 120, 0, 120, 60, '', 'RATE_LIST'),
  ('TEST', 'Serotonin', 'EIA', 'Serum', '2 ml', 'Mon', '1 pm', '4th Day', 4300, 0, 4300, 3800, '', 'RATE_LIST'),
  ('TEST', 'SGOT/ALT', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 80, 0, 80, 50, '', 'RATE_LIST'),
  ('TEST', 'SGPT/AST', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 80, 0, 80, 50, '', 'RATE_LIST'),
  ('TEST', 'SHBG (Sex Hormone Binding Globulin)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 700, 0, 700, 600, '', 'RATE_LIST'),
  ('TEST', 'Sickling Test', 'Microscopy', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 200, 0, 200, 100, '', 'RATE_LIST'),
  ('TEST', 'Sm (Smith) Antibody-IgG', 'EIA', 'Serum', '2 ml', 'Wed, Sat', '1 pm', '3rd Day', 1200, 0, 1200, 900, '', 'RATE_LIST'),
  ('TEST', 'Smear for Filaria (Microfilaria)', 'Microscopy', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 250, 0, 250, 150, '', 'RATE_LIST'),
  ('TEST', 'Smear for Malaria Parasite (MP Smear)', 'Microscopy', 'EDTA Blood', '2 ml', 'Daily', '', 'Next Day', 250, 0, 250, 120, '', 'RATE_LIST'),
  ('TEST', 'Sodium- Serum', 'ISE', 'Serum', '2 ml', 'Daily', '', 'Same Day', 100, 0, 100, 50, '', 'RATE_LIST'),
  ('TEST', 'Sodium- Urine (24 hrs)', 'ISE', 'Urine', '10 ml', 'Daily', '', 'Same Day', 150, 0, 150, 100, '', 'RATE_LIST'),
  ('TEST', 'Sodium- Urine (Spot)', 'ISE', 'Urine', '', 'Daily', '', 'Same Day', 120, 0, 120, 90, '', 'RATE_LIST'),
  ('TEST', 'Soluble Liver Antigen (SLA)', 'EIA', 'Serum', '2 ml', 'Thu', '1 pm', '3rd Day', 1500, 0, 1500, 1200, '', 'RATE_LIST'),
  ('TEST', 'Specific Gravity', 'IC', 'Urine', '10 ml', 'Daily', '', 'Same Day', 50, 0, 50, 40, '', 'RATE_LIST'),
  ('TEST', 'Stone Analysis', 'Biochemical', 'Urinary Stone', '', 'Daily', '1 pm', '3rd Day', 900, 0, 900, 750, '', 'RATE_LIST'),
  ('TEST', 'T3-Total (Triiodothyronine)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 120, 0, 120, 60, '', 'RATE_LIST'),
  ('TEST', 'T4-Total (Thyroxine)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 120, 0, 120, 60, '', 'RATE_LIST'),
  ('TEST', 'Tacrolimus', 'CMIA', 'EDTA Blood', '2 ml', 'Daily', '1 pm', '3rd Day', 2500, 0, 2500, 2000, '', 'RATE_LIST'),
  ('TEST', 'TB Gold/Quantiferon/IGRA', 'ELISA', 'Na+ or Li Heparin Blood', '3 ml', 'Daily', '1 pm', 'Next Day', 2500, 0, 2500, 2000, '', 'RATE_LIST'),
  ('TEST', 'TB PCR (Mycobacterium tuberculosis)', 'RT PCR', 'Body Fluids', '', 'Daily', '1 pm', 'Next Day', 2000, 0, 2000, 1300, '', 'RATE_LIST'),
  ('TEST', 'Testosterone- Free', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 800, 0, 800, 600, '', 'RATE_LIST'),
  ('TEST', 'Testosterone- Total', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 450, 0, 450, 220, '', 'RATE_LIST'),
  ('TEST', 'TFT (Thyroid Function Tests)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 300, 0, 300, 130, '', 'RATE_LIST'),
  ('TEST', 'Thyroglobulin (TG)', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 700, 0, 700, 400, '', 'RATE_LIST'),
  ('TEST', 'Thyroid Profile-1 (TFT, FT3, FT4 & TPO)', 'CLIA', 'Serum', '3 ml', 'Daily', '', 'Same Day', 1200, 0, 1200, 600, '', 'RATE_LIST'),
  ('TEST', 'Thyroid Profile-2 (TFT, FT3, FT4, ATG & TPO)', 'CLIA', 'Serum', '3 ml', 'Daily', '1 pm', 'Same Day', 1800, 0, 1800, 1200, '', 'RATE_LIST'),
  ('TEST', 'TIBC (Total Iron Binding Capacity)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 350, 0, 350, 250, '', 'RATE_LIST'),
  ('TEST', 'Tissue transglutaminase (TTG)- IgA', 'EIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 1500, 0, 1500, 1000, '', 'RATE_LIST'),
  ('TEST', 'Tissue transglutaminase (TTG)- IgG', 'EIA', 'Serum', '2 ml', 'Tue', '1 pm', '3rd Day', 1500, 0, 1500, 1100, '', 'RATE_LIST'),
  ('TEST', 'ToRCH Panel- IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1200, 0, 1200, 700, '', 'RATE_LIST'),
  ('TEST', 'ToRCH Panel- IgG & IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 2000, 0, 2000, 1200, '', 'RATE_LIST'),
  ('TEST', 'ToRCH Panel- IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 1200, 0, 1200, 700, '', 'RATE_LIST'),
  ('TEST', 'Total Count (TC)', 'Automated/Manual', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 30, 0, 30, 20, '', 'RATE_LIST'),
  ('TEST', 'Toxoplasma- IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 450, 0, 450, 300, '', 'RATE_LIST'),
  ('TEST', 'Toxoplasma- IgM', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 450, 0, 450, 300, '', 'RATE_LIST'),
  ('TEST', 'Toxoplasma Avidity - IgG', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 700, 0, 700, 500, '', 'RATE_LIST'),
  ('TEST', 'TPHA (Treponema Pallidum Hemagglutination Assay)', 'Agglutination', 'Serum', '2 ml', 'Daily', '', 'Same Day', 250, 0, 250, 170, '', 'RATE_LIST'),
  ('TEST', 'Transferrin Saturation (TSA)', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 850, 0, 850, 550, '', 'RATE_LIST'),
  ('TEST', 'Triglycerides', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 100, 0, 100, 60, '', 'RATE_LIST'),
  ('TEST', 'Troponin-I (Qualitative)', 'IC', 'Serum', '2 ml', 'Daily', '', 'Same Day', 400, 0, 400, 250, '', 'RATE_LIST'),
  ('TEST', 'Troponin-I (Quantitative)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 600, 0, 600, 350, '', 'RATE_LIST'),
  ('TEST', 'Troponin-T (Qualitative)', 'IC', 'EDTA Blood', '2 ml', 'Daily', '', 'Same Day', 600, 0, 600, 450, '', 'RATE_LIST'),
  ('TEST', 'TSH (Thyroid Stimulating Hormone)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 150, 0, 150, 70, '', 'RATE_LIST'),
  ('TEST', 'TSH Receptor Antibody', 'ECLIA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 3500, 0, 3500, 3000, '', 'RATE_LIST'),
  ('TEST', 'Typhi Dot / Salmonella Typhi-IgM', 'IC', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 500, 0, 500, 350, '', 'RATE_LIST'),
  ('TEST', 'Urea-Serum', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 80, 0, 80, 50, '', 'RATE_LIST'),
  ('TEST', 'Urea-Urine (24 hrs)', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 100, 0, 100, 50, '', 'RATE_LIST'),
  ('TEST', 'Urea-Urine (Spot)', 'Biochemical', 'Urine', '10 ml', 'Daily', '', 'Same Day', 80, 0, 80, 60, '', 'RATE_LIST'),
  ('TEST', 'Uric Acid-Serum', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 80, 0, 80, 50, '', 'RATE_LIST')
) AS v(test_type, name, method, sample, volume, scheduled_days, cut_of_time,
       reporting_time, rate, discount_percent, amount, lab_rate, internal_note, source)
ON CONFLICT ((lower(name))) DO NOTHING;

INSERT INTO app.lab_test
  (test_type, name, method, sample, volume, scheduled_days, cut_of_time,
   reporting_time, rate, discount_percent, amount, lab_rate, internal_note,
   source, created_by, updated_by)
SELECT v.*, 'Rate list import', 'Rate list import'
FROM (VALUES
  ('TEST', 'Uric Acid-Urine', 'Biochemical', '24 hrs/Spot Urine', '10 ml', 'Daily', '', '3rd Day', 150, 0, 150, 100, '', 'RATE_LIST'),
  ('TEST', 'Urine Analysis', 'Biochemical, Microscopy', 'Urine', '50 ml', 'Daily', '', 'Same Day', 50, 0, 50, 30, '', 'RATE_LIST'),
  ('TEST', 'Urobilinogen', 'IC', 'Urine', '10 ml', 'Daily', '', 'Same Day', 50, 0, 50, 40, '', 'RATE_LIST'),
  ('TEST', 'Valproic Acid', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '3rd Day', 650, 0, 650, 500, '', 'RATE_LIST'),
  ('TEST', 'Varicella zoster Antibody- IgG', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 1500, 0, 1500, 1200, '', 'RATE_LIST'),
  ('TEST', 'Varicella zoster Antibody- IgM', 'CLIA', 'Serum', '2 ml', 'Daily', '1 pm', '4th Day', 1500, 0, 1500, 1200, '', 'RATE_LIST'),
  ('TEST', 'VDRL-ELISA', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 400, 0, 400, 200, '', 'RATE_LIST'),
  ('TEST', 'VDRL-Screening', 'IC', 'Serum', '2 ml', 'Daily', '', 'Same Day', 100, 0, 100, 70, '', 'RATE_LIST'),
  ('TEST', 'Vitamin A', 'HPLC', 'Serum/EDTA Plasma', '3 ml', 'Tue, Fri', '1 pm', '4th Day', 4000, 0, 4000, 3600, '', 'RATE_LIST'),
  ('TEST', 'Vitamin B complex profile (B1, B2, B3, B5, B6, B7, B9)', 'LC MS/MS', 'Serum', '2 ml', 'Daily', '1 pm', '1 week', 5000, 0, 5000, 4500, '', 'RATE_LIST'),
  ('TEST', 'Vitamin B1', 'HPLC', 'EDTA Blood', '3 ml', 'Mon', '1 pm', '4th Day', 3500, 0, 3500, 3000, '', 'RATE_LIST'),
  ('TEST', 'Vitamin B12 (Cyanocobalamin)', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 650, 0, 650, 300, '', 'RATE_LIST'),
  ('TEST', 'Vitamin B6 (Pyridoxine)', 'HPLC', 'EDTA Blood', '3 ml', 'Thu', '1 pm', '6th Day', 3300, 0, 3300, 2650, '', 'RATE_LIST'),
  ('TEST', 'Vitamin B9 (Folic Acid)', 'ELISA', 'Serum', '2 ml', 'Daily', '1 pm', 'Same Day', 800, 0, 800, 650, '', 'RATE_LIST'),
  ('TEST', 'Vitamin C (Ascorbic Acid)', 'HPLC', 'Fasting Serum', '2 ml', 'Sat', '1 pm', '5th Day', 3000, 0, 3000, 2500, '', 'RATE_LIST'),
  ('TEST', 'Vitamin D (25 OH Vit-D)-Total', 'CLIA', 'Serum', '2 ml', 'Daily', '', 'Same Day', 900, 0, 900, 600, '', 'RATE_LIST'),
  ('TEST', 'Vitamin E', 'HPLC', 'Serum/EDTA Plasma', '3 ml', 'Tue, Fri', '1 pm', '4th Day', 4000, 0, 4000, 3600, '', 'RATE_LIST'),
  ('TEST', 'Vitamin K1', 'HPLC', 'Serum', '5 ml', 'Daily', '1 pm', '20th Day', 4000, 0, 4000, 3700, '', 'RATE_LIST'),
  ('TEST', 'VMA (Vanillylmandelic Acid)-Urine (24 hrs)', 'LC-MS/MS HPLC', 'Urine', '50 ml', 'Daily', '1 pm', '3rd Day', 1400, 0, 1400, 900, '', 'RATE_LIST'),
  ('TEST', 'VMA (Vanillylmandelic Acid)-Urine (Spot)', 'LC-MS/MS HPLC', 'Urine', '50 ml', 'Daily', '1 pm', '3rd Day', 1400, 0, 1400, 900, '', 'RATE_LIST'),
  ('TEST', 'Water Analysis', 'Culture, Biochemical', 'Water', '4 Ltrs', 'Daily', '', '5th Day', 1000, 0, 1000, 900, '', 'RATE_LIST'),
  ('TEST', 'Weil Felix Test', 'Agglutination', 'Serum', '2 ml', 'Daily', '1 pm', 'Next Day (1 pm)', 500, 0, 500, 350, '', 'RATE_LIST'),
  ('TEST', 'Widal-Slide Test', 'Agglutination', 'Serum', '2 ml', 'Daily', '', 'Same Day', 150, 0, 150, 70, '', 'RATE_LIST'),
  ('TEST', 'Widal-Tube Test', 'Agglutination', 'Serum', '2 ml', 'Daily', '1 pm', 'Next Day (1 pm)', 200, 0, 200, 100, '', 'RATE_LIST'),
  ('TEST', 'Zinc', 'Biochemical', 'Serum', '2 ml', 'Daily', '', 'Same Day', 500, 0, 500, 350, '', 'RATE_LIST')
) AS v(test_type, name, method, sample, volume, scheduled_days, cut_of_time,
       reporting_time, rate, discount_percent, amount, lab_rate, internal_note, source)
ON CONFLICT ((lower(name))) DO NOTHING;
