import 'package:flutter/material.dart';

import '../home/product_showcase.dart';
import 'category_catalogue.dart';

/// Products shown on a sub-category listing.
///
/// Curated entries exist for the sub-categories the reference screens show.
/// Everything else falls back to a set generated from the sub-category's own
/// name, so a listing always reflects the section it was opened from rather
/// than showing unrelated stock.
class ListingCatalogue {
  const ListingCatalogue._();

  static const Map<String, List<Product>> _curated = {
    'Skin Care': [
      Product(
        name: 'Skinshine Spf 30 Sunscreen Lotion 100ml',
        pack: 'Tube of 100ml',
        price: '191',
        mrp: '239',
        discountLabel: '20% OFF',
        icon: Icons.wb_sunny_outlined,
        image: 'assets/products/skinshine_sunscreen.png',
      ),
      Product(
        name: 'Soft Soles Cream 30gm',
        pack: 'Tube of 30g',
        price: '96',
        mrp: '120',
        discountLabel: '20% OFF',
        icon: Icons.spa_outlined,
        image: 'assets/products/soft_soles_cream.png',
      ),
      Product(
        name: 'Cetaphil Pro Oil Control Spf 30 Moisturizing Lotion 120ml',
        pack: 'Bottle of 120ml',
        price: '1,089',
        mrp: '1,171',
        discountLabel: '7% OFF',
        icon: Icons.water_drop_outlined,
        image: 'assets/products/cetaphil_pro_oil.png',
      ),
      Product(
        name: 'UV Doux Sunscreen Gel 60gm',
        pack: 'Tube of 60g',
        price: '552',
        mrp: '600',
        discountLabel: '8% OFF',
        icon: Icons.shield_moon_outlined,
        image: 'assets/products/uv_doux_sunscreen.png',
      ),
      Product(
        name: 'SunShade Ultra Matte Spf 50',
        pack: 'Tube of 50g',
        price: '360',
        mrp: '450',
        discountLabel: '20% OFF',
        icon: Icons.beach_access_outlined,
        image: 'assets/products/sunshade_matte.png',
      ),
      Product(
        name: 'Moisture Lock Body Lotion 300ml',
        pack: 'Bottle of 300ml',
        price: '288',
        mrp: '360',
        discountLabel: '20% OFF',
        icon: Icons.opacity_outlined,
        image: 'assets/products/moisture_lock_lotion.png',
      ),
      Product(
        name: 'Hydrating Hyaluronic Acid Serum 30ml',
        pack: 'Bottle of 30ml',
        price: '499',
        mrp: '699',
        discountLabel: '28% OFF',
        icon: Icons.water_drop_outlined,
        image: 'assets/categories/bundle_skincare.png',
      ),
      Product(
        name: 'Brightening Vitamin C Face Wash 100ml',
        pack: 'Tube of 100ml',
        price: '225',
        mrp: '299',
        discountLabel: '25% OFF',
        icon: Icons.face_retouching_natural_outlined,
        image: 'assets/categories/bundle_skincare.png',
      ),
    ],
    'Hair Care': [
      Product(
        name: 'Anti-Hairfall Shampoo 340ml',
        pack: 'Bottle of 340ml',
        price: '379',
        mrp: '475',
        discountLabel: '20% OFF',
        icon: Icons.shower_outlined,
        image: 'assets/categories/bundle_haircare.png',
      ),
      Product(
        name: 'Rosemary Hair Growth Oil 100ml',
        pack: 'Bottle of 100ml',
        price: '249',
        mrp: '330',
        discountLabel: '24% OFF',
        icon: Icons.local_florist_outlined,
        image: 'assets/categories/bundle_haircare.png',
      ),
      Product(
        name: 'Ketoconazole Anti-Dandruff Shampoo',
        pack: 'Bottle of 100ml',
        price: '318',
        mrp: '380',
        discountLabel: '16% OFF',
        icon: Icons.science_outlined,
        image: 'assets/categories/bundle_haircare.png',
      ),
      Product(
        name: 'Keratin Repair Conditioner 200ml',
        pack: 'Bottle of 200ml',
        price: '295',
        mrp: '369',
        discountLabel: '20% OFF',
        icon: Icons.auto_awesome_outlined,
        image: 'assets/categories/bundle_haircare.png',
      ),
      Product(
        name: 'Biotin Hair Strengthening Serum 50ml',
        pack: 'Bottle of 50ml',
        price: '449',
        mrp: '599',
        discountLabel: '25% OFF',
        icon: Icons.sanitizer_outlined,
        image: 'assets/categories/bundle_haircare.png',
      ),
      Product(
        name: 'Onion & Black Seed Hair Mask 200g',
        pack: 'Jar of 200g',
        price: '350',
        mrp: '450',
        discountLabel: '22% OFF',
        icon: Icons.spa_outlined,
        image: 'assets/categories/bundle_haircare.png',
      ),
    ],
    'Oral Care': [
      Product(
        name: 'Sensitive Relief Toothpaste 150gm',
        pack: 'Tube of 150g',
        price: '178',
        mrp: '215',
        discountLabel: '17% OFF',
        icon: Icons.clean_hands_outlined,
        image: 'assets/categories/bundle_oralcare.png',
      ),
      Product(
        name: 'Antiseptic Mouthwash 500ml',
        pack: 'Bottle of 500ml',
        price: '221',
        mrp: '260',
        discountLabel: '15% OFF',
        icon: Icons.local_drink_outlined,
        image: 'assets/categories/bundle_oralcare.png',
      ),
      Product(
        name: 'Soft Bristle Toothbrush Pack of 3',
        pack: 'Pack of 3',
        price: '135',
        mrp: '180',
        discountLabel: '25% OFF',
        icon: Icons.cleaning_services_outlined,
        image: 'assets/categories/bundle_oralcare.png',
      ),
      Product(
        name: 'Dental Floss Picks 50 Count',
        pack: 'Pack of 50',
        price: '149',
        mrp: '199',
        discountLabel: '25% OFF',
        icon: Icons.line_weight_rounded,
        image: 'assets/categories/bundle_oralcare.png',
      ),
      Product(
        name: 'Teeth Whitening Foam Rinse 100ml',
        pack: 'Bottle of 100ml',
        price: '299',
        mrp: '399',
        discountLabel: '25% OFF',
        icon: Icons.auto_fix_high_outlined,
        image: 'assets/categories/bundle_oralcare.png',
      ),
      Product(
        name: 'Herbal Clove & Neem Toothpaste 200g',
        pack: 'Tube of 200g',
        price: '120',
        mrp: '150',
        discountLabel: '20% OFF',
        icon: Icons.eco_outlined,
        image: 'assets/categories/bundle_oralcare.png',
      ),
    ],
    'Bath & Body': [
      Product(
        name: 'Deep Moisture Body Wash 500ml',
        pack: 'Bottle of 500ml',
        price: '299',
        mrp: '399',
        discountLabel: '25% OFF',
        icon: Icons.shower_outlined,
        image: 'assets/categories/bundle_bathbody.png',
      ),
      Product(
        name: 'Exfoliating Arabica Coffee Scrub 200g',
        pack: 'Jar of 200g',
        price: '349',
        mrp: '499',
        discountLabel: '30% OFF',
        icon: Icons.grain_outlined,
        image: 'assets/categories/bundle_bathbody.png',
      ),
      Product(
        name: 'Shea Butter Nourishing Bar Soap (Pack of 3)',
        pack: 'Pack of 3 (125g each)',
        price: '180',
        mrp: '240',
        discountLabel: '25% OFF',
        icon: Icons.soap_outlined,
        image: 'assets/categories/bundle_bathbody.png',
      ),
      Product(
        name: 'Cocoa Butter Intensive Body Lotion 400ml',
        pack: 'Bottle of 400ml',
        price: '320',
        mrp: '425',
        discountLabel: '24% OFF',
        icon: Icons.opacity_outlined,
        image: 'assets/products/moisture_lock_lotion.png',
      ),
      Product(
        name: 'Refreshing Tea Tree Shower Gel 250ml',
        pack: 'Bottle of 250ml',
        price: '215',
        mrp: '275',
        discountLabel: '21% OFF',
        icon: Icons.nature_outlined,
        image: 'assets/categories/bundle_bathbody.png',
      ),
      Product(
        name: 'Calming Lavender Bath Salts 300g',
        pack: 'Jar of 300g',
        price: '265',
        mrp: '350',
        discountLabel: '24% OFF',
        icon: Icons.spa_outlined,
        image: 'assets/categories/bundle_bathbody.png',
      ),
    ],
    'Men Grooming': [
      Product(
        name: 'Activated Charcoal Men\'s Face Wash 100ml',
        pack: 'Tube of 100ml',
        price: '199',
        mrp: '260',
        discountLabel: '23% OFF',
        icon: Icons.face_outlined,
        image: 'assets/categories/bundle_mengrooming.png',
      ),
      Product(
        name: 'Beard Growth Oil & Softener 50ml',
        pack: 'Bottle of 50ml',
        price: '299',
        mrp: '399',
        discountLabel: '25% OFF',
        icon: Icons.brush_outlined,
        image: 'assets/categories/bundle_mengrooming.png',
      ),
      Product(
        name: 'All-in-One 3-in-1 Body & Hair Wash 300ml',
        pack: 'Bottle of 300ml',
        price: '275',
        mrp: '350',
        discountLabel: '21% OFF',
        icon: Icons.shower_outlined,
        image: 'assets/categories/bundle_mengrooming.png',
      ),
      Product(
        name: 'Cooling Shave Gel with Aloe Vera 150ml',
        pack: 'Tube of 150ml',
        price: '165',
        mrp: '210',
        discountLabel: '21% OFF',
        icon: Icons.content_cut_outlined,
        image: 'assets/categories/bundle_mengrooming.png',
      ),
      Product(
        name: 'Matte Finish Hair Styling Clay 85g',
        pack: 'Jar of 85g',
        price: '285',
        mrp: '375',
        discountLabel: '24% OFF',
        icon: Icons.style_outlined,
        image: 'assets/categories/bundle_mengrooming.png',
      ),
      Product(
        name: 'Anti-Pollution Men\'s Sunscreen Spf 50',
        pack: 'Tube of 50g',
        price: '330',
        mrp: '420',
        discountLabel: '21% OFF',
        icon: Icons.shield_outlined,
        image: 'assets/categories/bundle_mengrooming.png',
      ),
    ],
    'Feminine Care': [
      Product(
        name: 'Organic Cotton Ultra-Thin Pads (Pack of 30)',
        pack: 'Pack of 30 pads',
        price: '289',
        mrp: '380',
        discountLabel: '24% OFF',
        icon: Icons.favorite_outline_rounded,
        image: 'assets/categories/bundle_femininecare.png',
      ),
      Product(
        name: 'Gentle Intimate Hygiene Wash 100ml',
        pack: 'Bottle of 100ml',
        price: '175',
        mrp: '225',
        discountLabel: '22% OFF',
        icon: Icons.water_drop_outlined,
        image: 'assets/categories/bundle_femininecare.png',
      ),
      Product(
        name: 'Medical Grade Reusable Menstrual Cup',
        pack: '1 unit (with pouch)',
        price: '349',
        mrp: '499',
        discountLabel: '30% OFF',
        icon: Icons.all_inclusive_rounded,
        image: 'assets/categories/bundle_femininecare.png',
      ),
      Product(
        name: 'Breathable Everyday Panty Liners 40s',
        pack: 'Pack of 40',
        price: '145',
        mrp: '190',
        discountLabel: '23% OFF',
        icon: Icons.layers_outlined,
        image: 'assets/categories/bundle_femininecare.png',
      ),
      Product(
        name: 'Soothing Cramp Relief Warm Patches (Pack of 5)',
        pack: 'Pack of 5 patches',
        price: '199',
        mrp: '275',
        discountLabel: '27% OFF',
        icon: Icons.healing_outlined,
        image: 'assets/categories/bundle_femininecare.png',
      ),
    ],
    'Multivitamins': [
      Product(
        name: 'Zincovit Multivitamin Tablets',
        pack: 'Strip of 15 tablets',
        price: '106',
        mrp: '132',
        discountLabel: '20% OFF',
        icon: Icons.medication_liquid_outlined,
        image: 'assets/products/zincovit.png',
      ),
      Product(
        name: 'Daily Men Vitality Multivitamin Complex',
        pack: 'Bottle of 60 tablets',
        price: '499',
        mrp: '699',
        discountLabel: '28% OFF',
        icon: Icons.fitness_center_outlined,
        image: 'assets/categories/bundle_multivitamins.png',
      ),
      Product(
        name: 'Women Complete Daily Multivitamin + Minerals',
        pack: 'Bottle of 60 tablets',
        price: '525',
        mrp: '720',
        discountLabel: '27% OFF',
        icon: Icons.favorite_border_rounded,
        image: 'assets/categories/bundle_multivitamins.png',
      ),
      Product(
        name: 'Kids Chewable Multivitamin Gummies',
        pack: 'Bottle of 30 gummies',
        price: '299',
        mrp: '399',
        discountLabel: '25% OFF',
        icon: Icons.emoji_emotions_outlined,
        image: 'assets/categories/bundle_multivitamins.png',
      ),
      Product(
        name: 'Senior 50+ Vitality Multivitamin Tablets',
        pack: 'Bottle of 60 tablets',
        price: '575',
        mrp: '750',
        discountLabel: '23% OFF',
        icon: Icons.health_and_safety_outlined,
        image: 'assets/categories/bundle_multivitamins.png',
      ),
    ],
    'Vitamin D': [
      Product(
        name: 'Vitamin D3 60K Chewable Tablets',
        pack: 'Strip of 4 tablets',
        price: '128',
        mrp: '175',
        discountLabel: '27% OFF',
        icon: Icons.wb_sunny_outlined,
        image: 'assets/products/vitamin_d3.png',
      ),
      Product(
        name: 'Vitamin D3 + K2 Bone & Heart Support',
        pack: 'Bottle of 60 capsules',
        price: '450',
        mrp: '600',
        discountLabel: '25% OFF',
        icon: Icons.monitor_heart_outlined,
        image: 'assets/categories/bundle_vitamind.png',
      ),
      Product(
        name: 'High Potency D3 2000 IU Daily Tablets',
        pack: 'Bottle of 60 tablets',
        price: '320',
        mrp: '420',
        discountLabel: '23% OFF',
        icon: Icons.sunny_snowing,
        image: 'assets/categories/bundle_vitamind.png',
      ),
      Product(
        name: 'Vitamin D3 Pediatric Drops 15ml',
        pack: 'Bottle of 15ml',
        price: '95',
        mrp: '120',
        discountLabel: '20% OFF',
        icon: Icons.child_care_outlined,
        image: 'assets/categories/bundle_vitamind.png',
      ),
    ],
    'Protein Powder': [
      Product(
        name: '100% Whey Protein Isolate Chocolate 1kg',
        pack: 'Jar of 1kg',
        price: '1,999',
        mrp: '3,200',
        discountLabel: '38% OFF',
        icon: Icons.fitness_center_rounded,
        image: 'assets/products/protein_powder.png',
      ),
      Product(
        name: 'Plant-Based Organic Protein Vanilla 1kg',
        pack: 'Jar of 1kg',
        price: '1,699',
        mrp: '2,499',
        discountLabel: '32% OFF',
        icon: Icons.eco_outlined,
        image: 'assets/categories/bundle_protein.png',
      ),
      Product(
        name: 'Lean Muscle Mass Gainer Powder 2kg',
        pack: 'Tub of 2kg',
        price: '2,399',
        mrp: '3,500',
        discountLabel: '31% OFF',
        icon: Icons.sports_gymnastics_outlined,
        image: 'assets/categories/bundle_protein.png',
      ),
      Product(
        name: 'Daily Protein Blend Unflavoured 500g',
        pack: 'Pouch of 500g',
        price: '899',
        mrp: '1,250',
        discountLabel: '28% OFF',
        icon: Icons.inventory_2_outlined,
        image: 'assets/categories/bundle_protein.png',
      ),
    ],
    'Omega & Fish Oil': [
      Product(
        name: 'Triple Strength Omega-3 Fish Oil 1000mg',
        pack: 'Bottle of 30 capsules',
        price: '389',
        mrp: '520',
        discountLabel: '25% OFF',
        icon: Icons.set_meal_outlined,
        image: 'assets/products/omega3_fish_oil.png',
      ),
      Product(
        name: 'Wild Alaskan Salmon Oil EPA/DHA 60s',
        pack: 'Bottle of 60 softgels',
        price: '649',
        mrp: '899',
        discountLabel: '27% OFF',
        icon: Icons.phishing_outlined,
        image: 'assets/categories/bundle_omega3.png',
      ),
      Product(
        name: 'Flaxseed Oil 1000mg Vegetarian Omega-3',
        pack: 'Bottle of 60 capsules',
        price: '299',
        mrp: '420',
        discountLabel: '28% OFF',
        icon: Icons.nature_outlined,
        image: 'assets/categories/bundle_omega3.png',
      ),
      Product(
        name: 'Deep Sea Krill Oil Phospholipids 30s',
        pack: 'Bottle of 30 capsules',
        price: '799',
        mrp: '1,100',
        discountLabel: '27% OFF',
        icon: Icons.bubble_chart_outlined,
        image: 'assets/categories/bundle_omega3.png',
      ),
    ],
    'Calcium': [
      Product(
        name: 'Shelcal 500 Calcium + D3 15 Tablets',
        pack: 'Strip of 15 tablets',
        price: '118',
        mrp: '145',
        discountLabel: '19% OFF',
        icon: Icons.emoji_food_beverage_outlined,
        image: 'assets/products/shelcal_500.png',
      ),
      Product(
        name: 'Calcium Citrate Malate + Magnesium Complex',
        pack: 'Bottle of 60 tablets',
        price: '420',
        mrp: '560',
        discountLabel: '25% OFF',
        icon: Icons.medical_information_outlined,
        image: 'assets/categories/bundle_calcium.png',
      ),
      Product(
        name: 'Coral Calcium Complex with Trace Minerals',
        pack: 'Bottle of 60 tablets',
        price: '475',
        mrp: '625',
        discountLabel: '24% OFF',
        icon: Icons.terrain_outlined,
        image: 'assets/categories/bundle_calcium.png',
      ),
      Product(
        name: 'Chewable Calcium D3 for Kids (Pack of 30)',
        pack: 'Bottle of 30 tablets',
        price: '210',
        mrp: '275',
        discountLabel: '23% OFF',
        icon: Icons.child_care_outlined,
        image: 'assets/categories/bundle_calcium.png',
      ),
    ],
    'Immunity': [
      Product(
        name: 'SHIELD Immunity Plus Tablets 60s',
        pack: 'Bottle of 60 tablets',
        price: '449',
        mrp: '649',
        discountLabel: '31% OFF',
        icon: Icons.shield_outlined,
        image: 'assets/products/shield_immunity.png',
      ),
      Product(
        name: 'Vitamin C 1000mg + Zinc Effervescent 20s',
        pack: 'Tube of 20 tablets',
        price: '245',
        mrp: '350',
        discountLabel: '30% OFF',
        icon: Icons.bubble_chart_outlined,
        image: 'assets/categories/bundle_immunity.png',
      ),
      Product(
        name: 'Pure Chyawanprash Herbal Booster 1kg',
        pack: 'Jar of 1kg',
        price: '375',
        mrp: '499',
        discountLabel: '24% OFF',
        icon: Icons.energy_savings_leaf_outlined,
        image: 'assets/categories/bundle_immunity.png',
      ),
      Product(
        name: 'Giloy Tulsi Neem Immunity Drops 30ml',
        pack: 'Bottle of 30ml',
        price: '160',
        mrp: '210',
        discountLabel: '23% OFF',
        icon: Icons.water_drop_outlined,
        image: 'assets/categories/bundle_immunity.png',
      ),
      Product(
        name: 'Sambucus Black Elderberry Extract Capsules',
        pack: 'Bottle of 60 capsules',
        price: '580',
        mrp: '780',
        discountLabel: '25% OFF',
        icon: Icons.local_pharmacy_outlined,
        image: 'assets/categories/bundle_immunity.png',
      ),
    ],
    'Bone and Joint Care': [
      Product(
        name: 'Joint Pain Relief Roll-On 50ml',
        pack: 'Bottle of 50ml',
        price: '175',
        mrp: '225',
        discountLabel: '22% OFF',
        icon: Icons.accessibility_new_rounded,
        image: 'assets/categories/bundle_bonejoint.png',
      ),
      Product(
        name: 'Glucosamine Chondroitin Joint Support 60s',
        pack: 'Bottle of 60 tablets',
        price: '649',
        mrp: '899',
        discountLabel: '27% OFF',
        icon: Icons.medication_outlined,
        image: 'assets/categories/bundle_bonejoint.png',
      ),
      Product(
        name: 'Hydrolyzed Collagen Peptides Powder 200g',
        pack: 'Jar of 200g',
        price: '899',
        mrp: '1,299',
        discountLabel: '30% OFF',
        icon: Icons.fitness_center_rounded,
        image: 'assets/categories/bundle_bonejoint.png',
      ),
      Product(
        name: 'Ortho Knee Support Elastic Sleeve',
        pack: '1 pair',
        price: '349',
        mrp: '499',
        discountLabel: '30% OFF',
        icon: Icons.healing_outlined,
        image: 'assets/categories/bundle_bonejoint.png',
      ),
    ],
    'Digestive Care': [
      Product(
        name: 'Digene Acidity Relief Liquid 200ml',
        pack: 'Bottle of 200ml',
        price: '138',
        mrp: '175',
        discountLabel: '21% OFF',
        icon: Icons.local_dining_outlined,
        image: 'assets/categories/bundle_digestive.png',
      ),
      Product(
        name: 'Probiotic 30 Billion CFU Capsules',
        pack: 'Bottle of 30 capsules',
        price: '549',
        mrp: '750',
        discountLabel: '26% OFF',
        icon: Icons.science_outlined,
        image: 'assets/categories/bundle_digestive.png',
      ),
      Product(
        name: 'Pure Isabgol Psyllium Husk 100g',
        pack: 'Box of 100g',
        price: '125',
        mrp: '155',
        discountLabel: '19% OFF',
        icon: Icons.grain_outlined,
        image: 'assets/categories/bundle_digestive.png',
      ),
      Product(
        name: 'Digestive Enzyme Herbal Tablets 60s',
        pack: 'Bottle of 60 tablets',
        price: '240',
        mrp: '310',
        discountLabel: '22% OFF',
        icon: Icons.eco_outlined,
        image: 'assets/categories/bundle_digestive.png',
      ),
    ],
    'Eye Care': [
      Product(
        name: 'Refresh Tears Lubricant Eye Drops 10ml',
        pack: 'Bottle of 10ml',
        price: '128',
        mrp: '160',
        discountLabel: '20% OFF',
        icon: Icons.remove_red_eye_outlined,
        image: 'assets/categories/bundle_eyecare.png',
      ),
      Product(
        name: 'Lutein & Zeaxanthin Blue Light Shield 30s',
        pack: 'Bottle of 30 capsules',
        price: '465',
        mrp: '620',
        discountLabel: '25% OFF',
        icon: Icons.visibility_outlined,
        image: 'assets/categories/bundle_eyecare.png',
      ),
      Product(
        name: 'Cooling Cucumber Soothing Eye Gel 30g',
        pack: 'Tube of 30g',
        price: '195',
        mrp: '250',
        discountLabel: '22% OFF',
        icon: Icons.spa_outlined,
        image: 'assets/categories/bundle_eyecare.png',
      ),
    ],
    'Pain Relief': [
      Product(
        name: 'Volini Pain Relief Gel 30g',
        pack: 'Tube of 30g',
        price: '148',
        mrp: '195',
        discountLabel: '24% OFF',
        icon: Icons.healing_outlined,
        image: 'assets/products/volini_gel.png',
      ),
      Product(
        name: 'Moov Fast Pain Relief Spray 80g',
        pack: 'Can of 80g',
        price: '185',
        mrp: '230',
        discountLabel: '19% OFF',
        icon: Icons.shower_outlined,
        image: 'assets/categories/bundle_painrelief.png',
      ),
      Product(
        name: 'Dolo 650mg Paracetamol Tablets',
        pack: 'Strip of 15 tablets',
        price: '32',
        mrp: '35',
        discountLabel: '8% OFF',
        icon: Icons.medication_outlined,
        image: 'assets/products/dolo_650.png',
      ),
      Product(
        name: 'Reusable Hot & Cold Gel Pack for Pain',
        pack: '1 pack',
        price: '220',
        mrp: '300',
        discountLabel: '26% OFF',
        icon: Icons.ac_unit_outlined,
        image: 'assets/categories/bundle_painrelief.png',
      ),
    ],
    'Glucometers': [
      Product(
        name: 'Accu-Chek Active Glucometer Machine Kit',
        pack: 'Kit of 1 device + 10 strips',
        price: '1,199',
        mrp: '1,699',
        discountLabel: '29% OFF',
        icon: Icons.speed_rounded,
        image: 'assets/categories/bundle_glucometer.png',
      ),
      Product(
        name: 'OneTouch Select Plus Simple Monitor',
        pack: 'Kit of 1 device + 10 strips',
        price: '1,049',
        mrp: '1,450',
        discountLabel: '27% OFF',
        icon: Icons.monitor_heart_outlined,
        image: 'assets/categories/bundle_glucometer.png',
      ),
      Product(
        name: 'Contour Plus Blood Glucose Monitor',
        pack: 'Kit of 1 device',
        price: '999',
        mrp: '1,380',
        discountLabel: '27% OFF',
        icon: Icons.bloodtype_outlined,
        image: 'assets/categories/bundle_glucometer.png',
      ),
    ],
    'Test Strips': [
      Product(
        name: 'Accu-Chek Active Test Strips 50 Count',
        pack: 'Box of 50 strips',
        price: '899',
        mrp: '1,399',
        discountLabel: '36% OFF',
        icon: Icons.receipt_long_outlined,
        image: 'assets/products/accuchek_strips.png',
      ),
      Product(
        name: 'OneTouch Select Plus Test Strips 50s',
        pack: 'Box of 50 strips',
        price: '865',
        mrp: '1,299',
        discountLabel: '33% OFF',
        icon: Icons.receipt_long_outlined,
        image: 'assets/categories/bundle_teststrips.png',
      ),
      Product(
        name: 'Contour Plus Blood Glucose Strips 25s',
        pack: 'Box of 25 strips',
        price: '520',
        mrp: '750',
        discountLabel: '30% OFF',
        icon: Icons.receipt_long_outlined,
        image: 'assets/categories/bundle_teststrips.png',
      ),
    ],
    'Sugar Substitutes': [
      Product(
        name: 'Sugar Free Natura Sweetener Pellets 500s',
        pack: 'Jar of 500 pellets',
        price: '199',
        mrp: '260',
        discountLabel: '23% OFF',
        icon: Icons.coffee_outlined,
        image: 'assets/categories/bundle_sugarsubstitute.png',
      ),
      Product(
        name: 'Natural Stevia Sweetener Drops 50ml',
        pack: 'Bottle of 50ml',
        price: '215',
        mrp: '285',
        discountLabel: '24% OFF',
        icon: Icons.water_drop_outlined,
        image: 'assets/categories/bundle_sugarsubstitute.png',
      ),
      Product(
        name: 'Zero Calorie Erythritol Natural Sugar Jar 500g',
        pack: 'Jar of 500g',
        price: '380',
        mrp: '499',
        discountLabel: '23% OFF',
        icon: Icons.grain_outlined,
        image: 'assets/categories/bundle_sugarsubstitute.png',
      ),
    ],
    'Diabetic Food': [
      Product(
        name: 'Low GI Diabetic Flour Multigrain 1kg',
        pack: 'Pouch of 1kg',
        price: '240',
        mrp: '310',
        discountLabel: '22% OFF',
        icon: Icons.rice_bowl_outlined,
        image: 'assets/categories/bundle_diabeticfood.png',
      ),
      Product(
        name: 'Diabetic Nutrition Protein Drink Mix 400g',
        pack: 'Jar of 400g',
        price: '580',
        mrp: '750',
        discountLabel: '22% OFF',
        icon: Icons.local_cafe_outlined,
        image: 'assets/categories/bundle_diabeticfood.png',
      ),
      Product(
        name: 'Sugar-Free High Fiber Oats Cookies 200g',
        pack: 'Box of 200g',
        price: '135',
        mrp: '175',
        discountLabel: '22% OFF',
        icon: Icons.cookie_outlined,
        image: 'assets/categories/bundle_diabeticfood.png',
      ),
    ],
    'Foot Care': [
      Product(
        name: 'Diabetic Foot Cream for Hydration & Repair',
        pack: 'Tube of 100g',
        price: '245',
        mrp: '340',
        discountLabel: '27% OFF',
        icon: Icons.healing_outlined,
        image: 'assets/categories/bundle_footcare.png',
      ),
      Product(
        name: 'Intensive Cracked Heel Repair Balm 50g',
        pack: 'Tube of 50g',
        price: '165',
        mrp: '220',
        discountLabel: '25% OFF',
        icon: Icons.spa_outlined,
        image: 'assets/products/soft_soles_cream.png',
      ),
      Product(
        name: 'Gel Padded Diabetic Comfort Socks',
        pack: '1 pair',
        price: '299',
        mrp: '399',
        discountLabel: '25% OFF',
        icon: Icons.airline_seat_legroom_normal_rounded,
        image: 'assets/categories/bundle_footcare.png',
      ),
    ],
    'Insulin Support': [
      Product(
        name: 'Insulin Pen Needles 31G Ultra Fine (Pack of 100)',
        pack: 'Box of 100 needles',
        price: '780',
        mrp: '1,050',
        discountLabel: '25% OFF',
        icon: Icons.vaccines_outlined,
        image: 'assets/categories/bundle_insulinsupport.png',
      ),
      Product(
        name: 'Insulin Cooling Travel Case & Gel Packs',
        pack: '1 unit',
        price: '499',
        mrp: '699',
        discountLabel: '28% OFF',
        icon: Icons.cases_outlined,
        image: 'assets/categories/bundle_insulinsupport.png',
      ),
      Product(
        name: 'Alpha Lipoic Acid Diabetic Nerve Support 60s',
        pack: 'Bottle of 60 capsules',
        price: '540',
        mrp: '720',
        discountLabel: '25% OFF',
        icon: Icons.medical_services_outlined,
        image: 'assets/categories/bundle_insulinsupport.png',
      ),
    ],
  };

  /// Generated stand-ins, so a sub-category without curated entries still
  /// lists products that name the section they belong to.
  static List<Product> _generated(SubCategory item) {
    const packs = ['Pack of 1', 'Pack of 2', 'Bottle of 100ml', 'Strip of 10'];
    const prices = ['249', '399', '175', '520'];
    const mrps = ['320', '499', '220', '650'];
    const discounts = ['22% OFF', '20% OFF', '20% OFF', '20% OFF'];
    const prefixes = ['Daily', 'Advanced', 'Everyday', 'Complete'];

    return [
      for (var i = 0; i < 4; i++)
        Product(
          name: '${prefixes[i]} ${item.label} Essentials',
          pack: packs[i],
          price: prices[i],
          mrp: mrps[i],
          discountLabel: discounts[i],
          icon: item.icon,
          image: item.image,
        ),
    ];
  }

  static List<Product> forSubCategory(SubCategory item) {
    return _curated[item.label] ?? _generated(item);
  }

  /// Everything across a group, used by the listing's "All" chip.
  static List<Product> forGroup(CategoryGroup group) => [
    for (final item in group.items) ...forSubCategory(item),
  ];

  /// The deals strip: the steepest discounts in the current listing.
  static List<Product> topDeals(List<Product> products) {
    int percent(Product p) {
      final label = p.discountLabel;
      if (label == null) {
        return 0;
      }
      return int.tryParse(label.split('%').first.trim()) ?? 0;
    }

    final ranked = [...products]
      ..sort((a, b) => percent(b).compareTo(percent(a)));
    return ranked.take(5).toList();
  }

  /// The brand behind each curated product, powering the filter sheet's
  /// "Brands" facet. Anything not listed here — the generated stand-ins
  /// included — is the SHIELD house brand, so every product filters under
  /// exactly one brand.
  static const Map<String, String> _brandByProduct = {
    // Skin Care
    'Skinshine Spf 30 Sunscreen Lotion 100ml': 'Skinshine',
    'Soft Soles Cream 30gm': 'Dr. Foot',
    'Cetaphil Pro Oil Control Spf 30 Moisturizing Lotion 120ml': 'Cetaphil',
    'UV Doux Sunscreen Gel 60gm': 'UV Doux',
    'SunShade Ultra Matte Spf 50': 'SunShade',
    'Moisture Lock Body Lotion 300ml': 'Nivea',
    'Hydrating Hyaluronic Acid Serum 30ml': 'Minimalist',
    'Brightening Vitamin C Face Wash 100ml': 'Minimalist',
    // Hair Care
    'Anti-Hairfall Shampoo 340ml': 'Dove',
    'Rosemary Hair Growth Oil 100ml': 'WOW',
    'Ketoconazole Anti-Dandruff Shampoo': 'Nizral',
    'Keratin Repair Conditioner 200ml': "L'Oreal Paris",
    'Biotin Hair Strengthening Serum 50ml': 'WOW',
    'Onion & Black Seed Hair Mask 200g': 'Mamaearth',
    // Oral Care
    'Sensitive Relief Toothpaste 150gm': 'Sensodyne',
    'Antiseptic Mouthwash 500ml': 'Listerine',
    'Soft Bristle Toothbrush Pack of 3': 'Oral-B',
    'Dental Floss Picks 50 Count': 'Oral-B',
    'Teeth Whitening Foam Rinse 100ml': 'Colgate',
    'Herbal Clove & Neem Toothpaste 200g': 'Dabur',
    // Bath & Body
    'Deep Moisture Body Wash 500ml': 'Dove',
    'Exfoliating Arabica Coffee Scrub 200g': 'mCaffeine',
    'Shea Butter Nourishing Bar Soap (Pack of 3)': 'Pears',
    'Cocoa Butter Intensive Body Lotion 400ml': 'Nivea',
    'Refreshing Tea Tree Shower Gel 250ml': 'Himalaya',
    'Calming Lavender Bath Salts 300g': 'Khadi Natural',
    // Men Grooming
    'Activated Charcoal Men\'s Face Wash 100ml': 'Beardo',
    'Beard Growth Oil & Softener 50ml': 'Beardo',
    'All-in-One 3-in-1 Body & Hair Wash 300ml': 'The Man Company',
    'Cooling Shave Gel with Aloe Vera 150ml': 'Gillette',
    'Matte Finish Hair Styling Clay 85g': 'The Man Company',
    'Anti-Pollution Men\'s Sunscreen Spf 50': 'Nivea Men',
    // Feminine Care
    'Organic Cotton Ultra-Thin Pads (Pack of 30)': 'Whisper',
    'Gentle Intimate Hygiene Wash 100ml': 'Pee Safe',
    'Medical Grade Reusable Menstrual Cup': 'Sirona',
    'Breathable Everyday Panty Liners 40s': 'Stayfree',
    'Soothing Cramp Relief Warm Patches (Pack of 5)': 'Sirona',
    // Multivitamins
    'Zincovit Multivitamin Tablets': 'Zincovit',
    'Daily Men Vitality Multivitamin Complex': 'Centrum',
    'Women Complete Daily Multivitamin + Minerals': 'Centrum',
    'Kids Chewable Multivitamin Gummies': 'HealthKart',
    'Senior 50+ Vitality Multivitamin Tablets': 'Revital',
    // Vitamin D
    'Vitamin D3 60K Chewable Tablets': 'Uprise',
    'Vitamin D3 + K2 Bone & Heart Support': 'Carbamide Forte',
    'High Potency D3 2000 IU Daily Tablets': 'HealthKart',
    'Vitamin D3 Pediatric Drops 15ml': 'Calcirol',
    // Protein Powder
    '100% Whey Protein Isolate Chocolate 1kg': 'MuscleBlaze',
    'Plant-Based Organic Protein Vanilla 1kg': 'Plix',
    'Lean Muscle Mass Gainer Powder 2kg': 'MuscleBlaze',
    'Daily Protein Blend Unflavoured 500g': 'HealthKart',
    // Omega & Fish Oil
    'Triple Strength Omega-3 Fish Oil 1000mg': 'HealthKart',
    'Wild Alaskan Salmon Oil EPA/DHA 60s': 'Neuherbs',
    'Flaxseed Oil 1000mg Vegetarian Omega-3': 'Carbamide Forte',
    'Deep Sea Krill Oil Phospholipids 30s': 'Neuherbs',
    // Calcium
    'Shelcal 500 Calcium + D3 15 Tablets': 'Shelcal',
    'Calcium Citrate Malate + Magnesium Complex': 'Carbamide Forte',
    'Coral Calcium Complex with Trace Minerals': 'HealthKart',
    'Chewable Calcium D3 for Kids (Pack of 30)': 'Cipcal',
    // Immunity
    'SHIELD Immunity Plus Tablets 60s': 'SHIELD',
    'Vitamin C 1000mg + Zinc Effervescent 20s': 'HealthKart',
    'Pure Chyawanprash Herbal Booster 1kg': 'Dabur',
    'Giloy Tulsi Neem Immunity Drops 30ml': 'Zandu',
    'Sambucus Black Elderberry Extract Capsules': 'Carbamide Forte',
    // Bone and Joint Care
    'Joint Pain Relief Roll-On 50ml': 'Volini',
    'Glucosamine Chondroitin Joint Support 60s': 'HealthKart',
    'Hydrolyzed Collagen Peptides Powder 200g': 'MuscleBlaze',
    'Ortho Knee Support Elastic Sleeve': 'Tynor',
    // Digestive Care
    'Digene Acidity Relief Liquid 200ml': 'Digene',
    'Probiotic 30 Billion CFU Capsules': 'HealthKart',
    'Pure Isabgol Psyllium Husk 100g': 'Dabur',
    'Digestive Enzyme Herbal Tablets 60s': 'Himalaya',
    // Eye Care
    'Refresh Tears Lubricant Eye Drops 10ml': 'Refresh',
    'Lutein & Zeaxanthin Blue Light Shield 30s': 'HealthKart',
    'Cooling Cucumber Soothing Eye Gel 30g': 'Himalaya',
    // Pain Relief
    'Volini Pain Relief Gel 30g': 'Volini',
    'Moov Fast Pain Relief Spray 80g': 'Moov',
    'Dolo 650mg Paracetamol Tablets': 'Dolo',
    'Reusable Hot & Cold Gel Pack for Pain': 'Tynor',
    // Glucometers
    'Accu-Chek Active Glucometer Machine Kit': 'Accu-Chek',
    'OneTouch Select Plus Simple Monitor': 'OneTouch',
    'Contour Plus Blood Glucose Monitor': 'Contour',
    // Test Strips
    'Accu-Chek Active Test Strips 50 Count': 'Accu-Chek',
    'OneTouch Select Plus Test Strips 50s': 'OneTouch',
    'Contour Plus Blood Glucose Strips 25s': 'Contour',
    // Sugar Substitutes
    'Sugar Free Natura Sweetener Pellets 500s': 'Sugar Free',
    'Natural Stevia Sweetener Drops 50ml': 'Zevic',
    'Zero Calorie Erythritol Natural Sugar Jar 500g': 'So Sweet',
    // Diabetic Food
    'Low GI Diabetic Flour Multigrain 1kg': 'Diabliss',
    'Diabetic Nutrition Protein Drink Mix 400g': 'Protinex',
    'Sugar-Free High Fiber Oats Cookies 200g': 'RiteBite',
    // Foot Care
    'Diabetic Foot Cream for Hydration & Repair': 'Dr. Foot',
    'Intensive Cracked Heel Repair Balm 50g': 'Scholl',
    'Gel Padded Diabetic Comfort Socks': 'Tynor',
    // Insulin Support
    'Insulin Pen Needles 31G Ultra Fine (Pack of 100)': 'BD',
    'Insulin Cooling Travel Case & Gel Packs': 'Dia-Safe',
    'Alpha Lipoic Acid Diabetic Nerve Support 60s': 'Carbamide Forte',
  };

  /// The brand a product filters under. Falls back to the house brand so the
  /// "Brands" facet always accounts for every product in the listing.
  static String brandOf(Product product) =>
      _brandByProduct[product.name] ?? 'SHIELD';

  /// Distinct brands present across [group], alphabetically — the "Brands"
  /// facet's options.
  static List<String> brandsFor(CategoryGroup group) {
    final seen = <String>{
      for (final product in forGroup(group)) brandOf(product),
    };
    return seen.toList()..sort();
  }

  /// The group's sub-category labels, in catalogue order — the "Sub-categories"
  /// facet's options.
  static List<String> subCategoryLabels(CategoryGroup group) =>
      [for (final item in group.items) item.label];
}
